// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type OptionsResp struct {
	Count int64  `json:"count"`
	Data  string `json:"data"`
}

type UploadPolicyReq struct {
	FileName    string `json:"file_name"`              // 文件名
	FileType    string `json:"file_type"`              // 文件类型
	MaxFileSize int64  `json:"max_file_size,optional"` // 最大文件大小（字节），可选
}

type UploadPolicyResp struct {
	URL       string            `json:"url"`        // 上传 URL
	FormData  map[string]string `json:"form_data"`  // 表单数据
	ObjectKey string            `json:"object_key"` // 对象键
	ExpiresIn int64             `json:"expires_in"` // 过期时间（秒）
}

type UploadPresignReq struct {
	FileName string `json:"file_name"` // 文件名
	FileType string `json:"file_type"` // 文件类型，如: pdf, docx
}

type UploadPresignResp struct {
	UploadURL string `json:"upload_url"` // 预签名上传 URL
	ObjectKey string `json:"object_key"` // 对象键（文件路径）
	ExpiresIn int64  `json:"expires_in"` // 过期时间（秒）
}
