// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type AIWriteReq struct {
	ResumeID int64  `json:"resume_id,string"` // 简历ID
	ModuleID int64  `json:"module_id,string"` // 模块ID（对应 MongoDB 中的模块项）
	Info     string `json:"info,optional"`    // 额外提示信息
}

type Article struct {
	ArticleId    int64  `json:"articleId,string"`
	Title        string `json:"title"`
	Subtitle     string `json:"subtitle,optional"`
	Content      string `json:"content,optional"`
	ThumbnailUrl string `json:"thumbnailUrl,optional"`
	Status       int    `json:"status,string"`
	ViewCount    int    `json:"viewCount"`
	PublishTime  string `json:"publishTime,optional"`
	CreateTime   string `json:"createTime,optional"`
	UpdateTime   string `json:"updateTime,optional"`
}

type CityItem struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
}

type CreateSlotOrderReq struct {
	Quantity int32 `json:"quantity"` // 购买数量
}

type CreateSlotOrderResp struct {
	OrderID     string `json:"order_id"`     // 订单ID
	CodeURL     string `json:"code_url"`     // 微信支付二维码内容
	TotalAmount int64  `json:"total_amount"` // 总金额（分）
	ExpireTime  string `json:"expire_time"`  // 过期时间
}

type DictionaryItem struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
}

type DimensionInfo struct {
	DimensionID int64   `json:"dimension_id,string"` // 维度ID
	Title       string  `json:"title"`               // 维度标题
	Score       float64 `json:"score"`               // 得分
}

type GenerateResumeReq struct {
	Questions []QuestionAnswer `json:"questions"` // 问题答案列表
}

type GenerateResumeResp struct {
	TaskID string `json:"task_id"` // 任务ID
}

type GetArticleReq struct {
	ArticleId int64 `path:"articleId"`
}

type GetArticleResp struct {
	Article
}

type GetCitiesByInitialsReq struct {
	Initials string `form:"initials"` // 首字母列表，如: "abc"
}

type GetCitiesByInitialsResp struct {
	Data map[string][]CityItem `json:"data"` // key为首字母，value为城市列表
}

type GetDictionaryByTypeReq struct {
	Type string `form:"type"` // 字典类型
}

type GetDictionaryByTypeResp struct {
	Items []DictionaryItem `json:"items"`
}

type GetLevel2CitiesResp struct {
	Cities []CityItem `json:"cities"`
}

type GetResumeReq struct {
	ResumeID int64 `path:"resume_id"` // 简历ID
}

type GetResumeResp struct {
	ResumeID   int64        `json:"resume_id,string"` // 简历ID
	FileName   string       `json:"file_name"`        // 文件名
	Status     int32        `json:"status"`           // 状态
	TotalScore float64      `json:"total_score"`      // 总分
	Modules    []ModuleInfo `json:"modules"`          // 模块列表（含数据和得分）
	CreatedAt  string       `json:"created_at"`       // 创建时间
	UpdatedAt  string       `json:"updated_at"`       // 更新时间
}

type GetSlotOrderReq struct {
	OrderID string `path:"order_id"` // 订单ID
}

type GetSlotOrderResp struct {
	OrderID     string `json:"order_id"`         // 订单ID
	Status      string `json:"status"`           // 订单状态: pending/paid/expired/cancelled
	Quantity    int32  `json:"quantity"`         // 购买数量
	TotalAmount int64  `json:"total_amount"`     // 总金额（分）
	PaidAt      string `json:"paid_at,optional"` // 支付时间
	CreatedAt   string `json:"created_at"`       // 创建时间
}

type ListArticlesReq struct {
	PageNum  int    `form:"pageNum,default=1"`
	PageSize int    `form:"pageSize,default=10"`
	Title    string `form:"title,optional"`
}

type ListArticlesResp struct {
	Rows  []Article `json:"rows"`
	Total int64     `json:"total"`
}

type LoginReq struct {
	GrantType   string `json:"grant_type"`  // 授权类型
	Credentials string `json:"credentials"` // 凭证信息(JSON字符串)
}

type LoginResp struct {
	AccessToken string `json:"access_token"` // 授权令牌
	ExpireIn    int64  `json:"expire_in"`    // 授权令牌有效期
}

type ModuleInfo struct {
	ModuleID   int64                    `json:"module_id,string"` // 模块ID
	Title      string                   `json:"title"`            // 模块标题
	Score      float64                  `json:"score"`            // 模块得分
	Data       []map[string]interface{} `json:"data"`             // 模块数据
	Dimensions []DimensionInfo          `json:"dimensions"`       // 维度得分列表
}

type OptionsResp struct {
	Count int64  `json:"count"`
	Data  string `json:"data"`
}

type QuestionAnswer struct {
	Question string   `json:"question"` // 问题
	Answers  []string `json:"answers"`  // 答案列表
}

type SaveModuleReq struct {
	ResumeID int64                    `json:"resume_id,string"` // 简历ID
	ModuleID int64                    `json:"module_id,string"` // 模块ID
	Data     []map[string]interface{} `json:"data"`             // 模块数据
}

type SaveModuleResp struct {
	ModuleID   int64                    `json:"module_id,string"` // 模块ID
	Title      string                   `json:"title"`            // 模块标题
	Score      float64                  `json:"score"`            // 模块得分
	Data       []map[string]interface{} `json:"data"`             // 模块数据
	Dimensions []DimensionInfo          `json:"dimensions"`       // 维度得分列表
}

type SlotPayNotifyReq struct {
	OrderID    string `json:"order_id"`     // 订单ID
	OutTradeNo string `json:"out_trade_no"` // 微信支付订单号
	UserID     string `json:"user_id"`      // 用户ID
	Quantity   int32  `json:"quantity"`     // 购买数量
	Status     string `json:"status"`       // 支付状态: paid
	PaidAt     string `json:"paid_at"`      // 支付时间
	Sign       string `json:"sign"`         // 签名
}

type SlotPayNotifyResp struct {
	Success bool   `json:"success"` // 是否成功
	Message string `json:"message"` // 消息
}

type TaskStatusReq struct {
	TaskID string `path:"task_id"` // 任务ID
}

type TaskStatusResp struct {
	Status   string `json:"status"`             // 任务状态: PENDING/PROCESSING/SUCCESS/FAILURE/TIMEOUT
	ResumeID int64  `json:"resume_id,optional"` // 简历ID（成功时返回）
}

type UploadPolicyReq struct {
	FileName    string `json:"file_name"`              // 文件名
	FileType    string `json:"file_type"`              // 文件类型
	MaxFileSize int64  `json:"max_file_size,optional"` // 最大文件大小（字节），可选
}

type UploadPolicyResp struct {
	Data string `json:"data"` // 预签名数据
}

type UploadPresignReq struct {
	FileName string `json:"file_name"` // 文件名
	FileType string `json:"file_type"` // 文件类型，如: pdf, docx
}

type UploadPresignResp struct {
	UploadURL string `json:"upload_url"` // 预签名上传 URL
	ObjectKey string `json:"object_key"` // 对象键（文件路径）
	ExpiresIn int64  `json:"expires_in"` // 过期时间（秒）
}

type UploadResumeResp struct {
	TaskID string `json:"task_id"` // 任务ID（用于查询解析状态）
}
