// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cv2/internal/infra/ent/airecord"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AIRecord is the model entity for the AIRecord schema.
type AIRecord struct {
	config `json:"-"`
	// ID of the ent.
	// AI优化记录ID
	ID int64 `json:"id,omitempty"`
	// 用户ID
	UserID int64 `json:"user_id,omitempty"`
	// 租户ID
	TenantID string `json:"tenant_id,omitempty"`
	// 简历ID
	ResumeID int64 `json:"resume_id,omitempty"`
	// 模块ID
	ModuleID int64 `json:"module_id,omitempty"`
	// 优化信息
	Info string `json:"info,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AIRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case airecord.FieldID, airecord.FieldUserID, airecord.FieldResumeID, airecord.FieldModuleID:
			values[i] = new(sql.NullInt64)
		case airecord.FieldTenantID, airecord.FieldInfo:
			values[i] = new(sql.NullString)
		case airecord.FieldCreatedAt, airecord.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AIRecord fields.
func (_m *AIRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case airecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case airecord.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case airecord.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = value.String
			}
		case airecord.FieldResumeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field resume_id", values[i])
			} else if value.Valid {
				_m.ResumeID = value.Int64
			}
		case airecord.FieldModuleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field module_id", values[i])
			} else if value.Valid {
				_m.ModuleID = value.Int64
			}
		case airecord.FieldInfo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field info", values[i])
			} else if value.Valid {
				_m.Info = value.String
			}
		case airecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case airecord.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AIRecord.
// This includes values selected through modifiers, order, etc.
func (_m *AIRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AIRecord.
// Note that you need to call AIRecord.Unwrap() before calling this method if this AIRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AIRecord) Update() *AIRecordUpdateOne {
	return NewAIRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AIRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AIRecord) Unwrap() *AIRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AIRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AIRecord) String() string {
	var builder strings.Builder
	builder.WriteString("AIRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(_m.TenantID)
	builder.WriteString(", ")
	builder.WriteString("resume_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResumeID))
	builder.WriteString(", ")
	builder.WriteString("module_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModuleID))
	builder.WriteString(", ")
	builder.WriteString("info=")
	builder.WriteString(_m.Info)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AIRecords is a parsable slice of AIRecord.
type AIRecords []*AIRecord
