// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cv2/internal/infra/ent/airecord"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AIRecordCreate is the builder for creating a AIRecord entity.
type AIRecordCreate struct {
	config
	mutation *AIRecordMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *AIRecordCreate) SetUserID(v int64) *AIRecordCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *AIRecordCreate) SetTenantID(v string) *AIRecordCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetResumeID sets the "resume_id" field.
func (_c *AIRecordCreate) SetResumeID(v int64) *AIRecordCreate {
	_c.mutation.SetResumeID(v)
	return _c
}

// SetModuleID sets the "module_id" field.
func (_c *AIRecordCreate) SetModuleID(v int64) *AIRecordCreate {
	_c.mutation.SetModuleID(v)
	return _c
}

// SetInfo sets the "info" field.
func (_c *AIRecordCreate) SetInfo(v string) *AIRecordCreate {
	_c.mutation.SetInfo(v)
	return _c
}

// SetNillableInfo sets the "info" field if the given value is not nil.
func (_c *AIRecordCreate) SetNillableInfo(v *string) *AIRecordCreate {
	if v != nil {
		_c.SetInfo(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AIRecordCreate) SetCreatedAt(v time.Time) *AIRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AIRecordCreate) SetNillableCreatedAt(v *time.Time) *AIRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AIRecordCreate) SetUpdatedAt(v time.Time) *AIRecordCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AIRecordCreate) SetNillableUpdatedAt(v *time.Time) *AIRecordCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AIRecordCreate) SetID(v int64) *AIRecordCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AIRecordCreate) SetNillableID(v *int64) *AIRecordCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the AIRecordMutation object of the builder.
func (_c *AIRecordCreate) Mutation() *AIRecordMutation {
	return _c.mutation
}

// Save creates the AIRecord in the database.
func (_c *AIRecordCreate) Save(ctx context.Context) (*AIRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AIRecordCreate) SaveX(ctx context.Context) *AIRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AIRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AIRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AIRecordCreate) defaults() {
	if _, ok := _c.mutation.Info(); !ok {
		v := airecord.DefaultInfo
		_c.mutation.SetInfo(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := airecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := airecord.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := airecord.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AIRecordCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AIRecord.user_id"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "AIRecord.tenant_id"`)}
	}
	if _, ok := _c.mutation.ResumeID(); !ok {
		return &ValidationError{Name: "resume_id", err: errors.New(`ent: missing required field "AIRecord.resume_id"`)}
	}
	if _, ok := _c.mutation.ModuleID(); !ok {
		return &ValidationError{Name: "module_id", err: errors.New(`ent: missing required field "AIRecord.module_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AIRecord.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AIRecord.updated_at"`)}
	}
	return nil
}

func (_c *AIRecordCreate) sqlSave(ctx context.Context) (*AIRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AIRecordCreate) createSpec() (*AIRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &AIRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(airecord.Table, sqlgraph.NewFieldSpec(airecord.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(airecord.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(airecord.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.ResumeID(); ok {
		_spec.SetField(airecord.FieldResumeID, field.TypeInt64, value)
		_node.ResumeID = value
	}
	if value, ok := _c.mutation.ModuleID(); ok {
		_spec.SetField(airecord.FieldModuleID, field.TypeInt64, value)
		_node.ModuleID = value
	}
	if value, ok := _c.mutation.Info(); ok {
		_spec.SetField(airecord.FieldInfo, field.TypeString, value)
		_node.Info = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(airecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(airecord.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// AIRecordCreateBulk is the builder for creating many AIRecord entities in bulk.
type AIRecordCreateBulk struct {
	config
	err      error
	builders []*AIRecordCreate
}

// Save creates the AIRecord entities in the database.
func (_c *AIRecordCreateBulk) Save(ctx context.Context) ([]*AIRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AIRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AIRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AIRecordCreateBulk) SaveX(ctx context.Context) []*AIRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AIRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AIRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
