// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cv2/internal/infra/ent/city"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CityCreate is the builder for creating a City entity.
type CityCreate struct {
	config
	mutation *CityMutation
	hooks    []Hook
}

// SetParentID sets the "parent_id" field.
func (_c *CityCreate) SetParentID(v int64) *CityCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_c *CityCreate) SetNillableParentID(v *int64) *CityCreate {
	if v != nil {
		_c.SetParentID(*v)
	}
	return _c
}

// SetLevel sets the "level" field.
func (_c *CityCreate) SetLevel(v int) *CityCreate {
	_c.mutation.SetLevel(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *CityCreate) SetTitle(v string) *CityCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetInitial sets the "initial" field.
func (_c *CityCreate) SetInitial(v string) *CityCreate {
	_c.mutation.SetInitial(v)
	return _c
}

// SetNillableInitial sets the "initial" field if the given value is not nil.
func (_c *CityCreate) SetNillableInitial(v *string) *CityCreate {
	if v != nil {
		_c.SetInitial(*v)
	}
	return _c
}

// SetIsHot sets the "is_hot" field.
func (_c *CityCreate) SetIsHot(v bool) *CityCreate {
	_c.mutation.SetIsHot(v)
	return _c
}

// SetNillableIsHot sets the "is_hot" field if the given value is not nil.
func (_c *CityCreate) SetNillableIsHot(v *bool) *CityCreate {
	if v != nil {
		_c.SetIsHot(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CityCreate) SetCreatedAt(v time.Time) *CityCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CityCreate) SetNillableCreatedAt(v *time.Time) *CityCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CityCreate) SetUpdatedAt(v time.Time) *CityCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CityCreate) SetNillableUpdatedAt(v *time.Time) *CityCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CityCreate) SetID(v int64) *CityCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CityCreate) SetNillableID(v *int64) *CityCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddChildIDs adds the "children" edge to the City entity by IDs.
func (_c *CityCreate) AddChildIDs(ids ...int64) *CityCreate {
	_c.mutation.AddChildIDs(ids...)
	return _c
}

// AddChildren adds the "children" edges to the City entity.
func (_c *CityCreate) AddChildren(v ...*City) *CityCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChildIDs(ids...)
}

// SetParent sets the "parent" edge to the City entity.
func (_c *CityCreate) SetParent(v *City) *CityCreate {
	return _c.SetParentID(v.ID)
}

// Mutation returns the CityMutation object of the builder.
func (_c *CityCreate) Mutation() *CityMutation {
	return _c.mutation
}

// Save creates the City in the database.
func (_c *CityCreate) Save(ctx context.Context) (*City, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CityCreate) SaveX(ctx context.Context) *City {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CityCreate) defaults() {
	if _, ok := _c.mutation.ParentID(); !ok {
		v := city.DefaultParentID
		_c.mutation.SetParentID(v)
	}
	if _, ok := _c.mutation.Initial(); !ok {
		v := city.DefaultInitial
		_c.mutation.SetInitial(v)
	}
	if _, ok := _c.mutation.IsHot(); !ok {
		v := city.DefaultIsHot
		_c.mutation.SetIsHot(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := city.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := city.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := city.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CityCreate) check() error {
	if _, ok := _c.mutation.Level(); !ok {
		return &ValidationError{Name: "level", err: errors.New(`ent: missing required field "City.level"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "City.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := city.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "City.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsHot(); !ok {
		return &ValidationError{Name: "is_hot", err: errors.New(`ent: missing required field "City.is_hot"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "City.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "City.updated_at"`)}
	}
	return nil
}

func (_c *CityCreate) sqlSave(ctx context.Context) (*City, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CityCreate) createSpec() (*City, *sqlgraph.CreateSpec) {
	var (
		_node = &City{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(city.Table, sqlgraph.NewFieldSpec(city.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Level(); ok {
		_spec.SetField(city.FieldLevel, field.TypeInt, value)
		_node.Level = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(city.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Initial(); ok {
		_spec.SetField(city.FieldInitial, field.TypeString, value)
		_node.Initial = value
	}
	if value, ok := _c.mutation.IsHot(); ok {
		_spec.SetField(city.FieldIsHot, field.TypeBool, value)
		_node.IsHot = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(city.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(city.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   city.ChildrenTable,
			Columns: []string{city.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(city.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   city.ParentTable,
			Columns: []string{city.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(city.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ParentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CityCreateBulk is the builder for creating many City entities in bulk.
type CityCreateBulk struct {
	config
	err      error
	builders []*CityCreate
}

// Save creates the City entities in the database.
func (_c *CityCreateBulk) Save(ctx context.Context) ([]*City, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*City, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CityCreateBulk) SaveX(ctx context.Context) []*City {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
