// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cv2/internal/infra/ent/city"
	"cv2/internal/infra/ent/predicate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CityUpdate is the builder for updating City entities.
type CityUpdate struct {
	config
	hooks    []Hook
	mutation *CityMutation
}

// Where appends a list predicates to the CityUpdate builder.
func (_u *CityUpdate) Where(ps ...predicate.City) *CityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *CityUpdate) SetParentID(v int64) *CityUpdate {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *CityUpdate) SetNillableParentID(v *int64) *CityUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *CityUpdate) ClearParentID() *CityUpdate {
	_u.mutation.ClearParentID()
	return _u
}

// SetLevel sets the "level" field.
func (_u *CityUpdate) SetLevel(v int) *CityUpdate {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *CityUpdate) SetNillableLevel(v *int) *CityUpdate {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *CityUpdate) AddLevel(v int) *CityUpdate {
	_u.mutation.AddLevel(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *CityUpdate) SetTitle(v string) *CityUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *CityUpdate) SetNillableTitle(v *string) *CityUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetInitial sets the "initial" field.
func (_u *CityUpdate) SetInitial(v string) *CityUpdate {
	_u.mutation.SetInitial(v)
	return _u
}

// SetNillableInitial sets the "initial" field if the given value is not nil.
func (_u *CityUpdate) SetNillableInitial(v *string) *CityUpdate {
	if v != nil {
		_u.SetInitial(*v)
	}
	return _u
}

// ClearInitial clears the value of the "initial" field.
func (_u *CityUpdate) ClearInitial() *CityUpdate {
	_u.mutation.ClearInitial()
	return _u
}

// SetIsHot sets the "is_hot" field.
func (_u *CityUpdate) SetIsHot(v bool) *CityUpdate {
	_u.mutation.SetIsHot(v)
	return _u
}

// SetNillableIsHot sets the "is_hot" field if the given value is not nil.
func (_u *CityUpdate) SetNillableIsHot(v *bool) *CityUpdate {
	if v != nil {
		_u.SetIsHot(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CityUpdate) SetUpdatedAt(v time.Time) *CityUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddChildIDs adds the "children" edge to the City entity by IDs.
func (_u *CityUpdate) AddChildIDs(ids ...int64) *CityUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the City entity.
func (_u *CityUpdate) AddChildren(v ...*City) *CityUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// SetParent sets the "parent" edge to the City entity.
func (_u *CityUpdate) SetParent(v *City) *CityUpdate {
	return _u.SetParentID(v.ID)
}

// Mutation returns the CityMutation object of the builder.
func (_u *CityUpdate) Mutation() *CityMutation {
	return _u.mutation
}

// ClearChildren clears all "children" edges to the City entity.
func (_u *CityUpdate) ClearChildren() *CityUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to City entities by IDs.
func (_u *CityUpdate) RemoveChildIDs(ids ...int64) *CityUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to City entities.
func (_u *CityUpdate) RemoveChildren(v ...*City) *CityUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearParent clears the "parent" edge to the City entity.
func (_u *CityUpdate) ClearParent() *CityUpdate {
	_u.mutation.ClearParent()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CityUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CityUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := city.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CityUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := city.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "City.title": %w`, err)}
		}
	}
	return nil
}

func (_u *CityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(city.Table, city.Columns, sqlgraph.NewFieldSpec(city.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(city.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(city.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(city.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Initial(); ok {
		_spec.SetField(city.FieldInitial, field.TypeString, value)
	}
	if _u.mutation.InitialCleared() {
		_spec.ClearField(city.FieldInitial, field.TypeString)
	}
	if value, ok := _u.mutation.IsHot(); ok {
		_spec.SetField(city.FieldIsHot, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(city.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   city.ChildrenTable,
			Columns: []string{city.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(city.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   city.ChildrenTable,
			Columns: []string{city.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(city.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   city.ChildrenTable,
			Columns: []string{city.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(city.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   city.ParentTable,
			Columns: []string{city.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(city.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   city.ParentTable,
			Columns: []string{city.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(city.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{city.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CityUpdateOne is the builder for updating a single City entity.
type CityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CityMutation
}

// SetParentID sets the "parent_id" field.
func (_u *CityUpdateOne) SetParentID(v int64) *CityUpdateOne {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *CityUpdateOne) SetNillableParentID(v *int64) *CityUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *CityUpdateOne) ClearParentID() *CityUpdateOne {
	_u.mutation.ClearParentID()
	return _u
}

// SetLevel sets the "level" field.
func (_u *CityUpdateOne) SetLevel(v int) *CityUpdateOne {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *CityUpdateOne) SetNillableLevel(v *int) *CityUpdateOne {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *CityUpdateOne) AddLevel(v int) *CityUpdateOne {
	_u.mutation.AddLevel(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *CityUpdateOne) SetTitle(v string) *CityUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *CityUpdateOne) SetNillableTitle(v *string) *CityUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetInitial sets the "initial" field.
func (_u *CityUpdateOne) SetInitial(v string) *CityUpdateOne {
	_u.mutation.SetInitial(v)
	return _u
}

// SetNillableInitial sets the "initial" field if the given value is not nil.
func (_u *CityUpdateOne) SetNillableInitial(v *string) *CityUpdateOne {
	if v != nil {
		_u.SetInitial(*v)
	}
	return _u
}

// ClearInitial clears the value of the "initial" field.
func (_u *CityUpdateOne) ClearInitial() *CityUpdateOne {
	_u.mutation.ClearInitial()
	return _u
}

// SetIsHot sets the "is_hot" field.
func (_u *CityUpdateOne) SetIsHot(v bool) *CityUpdateOne {
	_u.mutation.SetIsHot(v)
	return _u
}

// SetNillableIsHot sets the "is_hot" field if the given value is not nil.
func (_u *CityUpdateOne) SetNillableIsHot(v *bool) *CityUpdateOne {
	if v != nil {
		_u.SetIsHot(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CityUpdateOne) SetUpdatedAt(v time.Time) *CityUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddChildIDs adds the "children" edge to the City entity by IDs.
func (_u *CityUpdateOne) AddChildIDs(ids ...int64) *CityUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the City entity.
func (_u *CityUpdateOne) AddChildren(v ...*City) *CityUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// SetParent sets the "parent" edge to the City entity.
func (_u *CityUpdateOne) SetParent(v *City) *CityUpdateOne {
	return _u.SetParentID(v.ID)
}

// Mutation returns the CityMutation object of the builder.
func (_u *CityUpdateOne) Mutation() *CityMutation {
	return _u.mutation
}

// ClearChildren clears all "children" edges to the City entity.
func (_u *CityUpdateOne) ClearChildren() *CityUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to City entities by IDs.
func (_u *CityUpdateOne) RemoveChildIDs(ids ...int64) *CityUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to City entities.
func (_u *CityUpdateOne) RemoveChildren(v ...*City) *CityUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearParent clears the "parent" edge to the City entity.
func (_u *CityUpdateOne) ClearParent() *CityUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// Where appends a list predicates to the CityUpdate builder.
func (_u *CityUpdateOne) Where(ps ...predicate.City) *CityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CityUpdateOne) Select(field string, fields ...string) *CityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated City entity.
func (_u *CityUpdateOne) Save(ctx context.Context) (*City, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CityUpdateOne) SaveX(ctx context.Context) *City {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CityUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := city.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CityUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := city.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "City.title": %w`, err)}
		}
	}
	return nil
}

func (_u *CityUpdateOne) sqlSave(ctx context.Context) (_node *City, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(city.Table, city.Columns, sqlgraph.NewFieldSpec(city.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "City.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, city.FieldID)
		for _, f := range fields {
			if !city.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != city.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(city.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(city.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(city.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Initial(); ok {
		_spec.SetField(city.FieldInitial, field.TypeString, value)
	}
	if _u.mutation.InitialCleared() {
		_spec.ClearField(city.FieldInitial, field.TypeString)
	}
	if value, ok := _u.mutation.IsHot(); ok {
		_spec.SetField(city.FieldIsHot, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(city.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   city.ChildrenTable,
			Columns: []string{city.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(city.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   city.ChildrenTable,
			Columns: []string{city.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(city.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   city.ChildrenTable,
			Columns: []string{city.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(city.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   city.ParentTable,
			Columns: []string{city.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(city.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   city.ParentTable,
			Columns: []string{city.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(city.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &City{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{city.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
