// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cv2/internal/infra/ent/dictionary"
	"cv2/internal/infra/ent/predicate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DictionaryUpdate is the builder for updating Dictionary entities.
type DictionaryUpdate struct {
	config
	hooks    []Hook
	mutation *DictionaryMutation
}

// Where appends a list predicates to the DictionaryUpdate builder.
func (_u *DictionaryUpdate) Where(ps ...predicate.Dictionary) *DictionaryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *DictionaryUpdate) SetTitle(v string) *DictionaryUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *DictionaryUpdate) SetNillableTitle(v *string) *DictionaryUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *DictionaryUpdate) SetType(v string) *DictionaryUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *DictionaryUpdate) SetNillableType(v *string) *DictionaryUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetOrder sets the "order" field.
func (_u *DictionaryUpdate) SetOrder(v int) *DictionaryUpdate {
	_u.mutation.ResetOrder()
	_u.mutation.SetOrder(v)
	return _u
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_u *DictionaryUpdate) SetNillableOrder(v *int) *DictionaryUpdate {
	if v != nil {
		_u.SetOrder(*v)
	}
	return _u
}

// AddOrder adds value to the "order" field.
func (_u *DictionaryUpdate) AddOrder(v int) *DictionaryUpdate {
	_u.mutation.AddOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DictionaryUpdate) SetUpdatedAt(v time.Time) *DictionaryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DictionaryMutation object of the builder.
func (_u *DictionaryUpdate) Mutation() *DictionaryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DictionaryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DictionaryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DictionaryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DictionaryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DictionaryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dictionary.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DictionaryUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := dictionary.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Dictionary.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := dictionary.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Dictionary.type": %w`, err)}
		}
	}
	return nil
}

func (_u *DictionaryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dictionary.Table, dictionary.Columns, sqlgraph.NewFieldSpec(dictionary.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(dictionary.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(dictionary.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Order(); ok {
		_spec.SetField(dictionary.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrder(); ok {
		_spec.AddField(dictionary.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dictionary.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dictionary.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DictionaryUpdateOne is the builder for updating a single Dictionary entity.
type DictionaryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DictionaryMutation
}

// SetTitle sets the "title" field.
func (_u *DictionaryUpdateOne) SetTitle(v string) *DictionaryUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *DictionaryUpdateOne) SetNillableTitle(v *string) *DictionaryUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *DictionaryUpdateOne) SetType(v string) *DictionaryUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *DictionaryUpdateOne) SetNillableType(v *string) *DictionaryUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetOrder sets the "order" field.
func (_u *DictionaryUpdateOne) SetOrder(v int) *DictionaryUpdateOne {
	_u.mutation.ResetOrder()
	_u.mutation.SetOrder(v)
	return _u
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_u *DictionaryUpdateOne) SetNillableOrder(v *int) *DictionaryUpdateOne {
	if v != nil {
		_u.SetOrder(*v)
	}
	return _u
}

// AddOrder adds value to the "order" field.
func (_u *DictionaryUpdateOne) AddOrder(v int) *DictionaryUpdateOne {
	_u.mutation.AddOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DictionaryUpdateOne) SetUpdatedAt(v time.Time) *DictionaryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DictionaryMutation object of the builder.
func (_u *DictionaryUpdateOne) Mutation() *DictionaryMutation {
	return _u.mutation
}

// Where appends a list predicates to the DictionaryUpdate builder.
func (_u *DictionaryUpdateOne) Where(ps ...predicate.Dictionary) *DictionaryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DictionaryUpdateOne) Select(field string, fields ...string) *DictionaryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Dictionary entity.
func (_u *DictionaryUpdateOne) Save(ctx context.Context) (*Dictionary, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DictionaryUpdateOne) SaveX(ctx context.Context) *Dictionary {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DictionaryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DictionaryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DictionaryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dictionary.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DictionaryUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := dictionary.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Dictionary.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := dictionary.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Dictionary.type": %w`, err)}
		}
	}
	return nil
}

func (_u *DictionaryUpdateOne) sqlSave(ctx context.Context) (_node *Dictionary, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dictionary.Table, dictionary.Columns, sqlgraph.NewFieldSpec(dictionary.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Dictionary.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dictionary.FieldID)
		for _, f := range fields {
			if !dictionary.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dictionary.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(dictionary.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(dictionary.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Order(); ok {
		_spec.SetField(dictionary.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrder(); ok {
		_spec.AddField(dictionary.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dictionary.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Dictionary{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dictionary.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
