// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cv2/internal/infra/ent/dimension"
	"cv2/internal/infra/ent/module"
	"cv2/internal/infra/ent/predicate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// DimensionUpdate is the builder for updating Dimension entities.
type DimensionUpdate struct {
	config
	hooks    []Hook
	mutation *DimensionMutation
}

// Where appends a list predicates to the DimensionUpdate builder.
func (_u *DimensionUpdate) Where(ps ...predicate.Dimension) *DimensionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetModuleID sets the "module_id" field.
func (_u *DimensionUpdate) SetModuleID(v int64) *DimensionUpdate {
	_u.mutation.SetModuleID(v)
	return _u
}

// SetNillableModuleID sets the "module_id" field if the given value is not nil.
func (_u *DimensionUpdate) SetNillableModuleID(v *int64) *DimensionUpdate {
	if v != nil {
		_u.SetModuleID(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *DimensionUpdate) SetDescription(v string) *DimensionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DimensionUpdate) SetNillableDescription(v *string) *DimensionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *DimensionUpdate) SetTitle(v string) *DimensionUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *DimensionUpdate) SetNillableTitle(v *string) *DimensionUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetJudgment sets the "judgment" field.
func (_u *DimensionUpdate) SetJudgment(v []map[string]interface{}) *DimensionUpdate {
	_u.mutation.SetJudgment(v)
	return _u
}

// AppendJudgment appends value to the "judgment" field.
func (_u *DimensionUpdate) AppendJudgment(v []map[string]interface{}) *DimensionUpdate {
	_u.mutation.AppendJudgment(v)
	return _u
}

// ClearJudgment clears the value of the "judgment" field.
func (_u *DimensionUpdate) ClearJudgment() *DimensionUpdate {
	_u.mutation.ClearJudgment()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DimensionUpdate) SetUpdatedAt(v time.Time) *DimensionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DimensionUpdate) SetDeletedAt(v time.Time) *DimensionUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DimensionUpdate) SetNillableDeletedAt(v *time.Time) *DimensionUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DimensionUpdate) ClearDeletedAt() *DimensionUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetModule sets the "module" edge to the Module entity.
func (_u *DimensionUpdate) SetModule(v *Module) *DimensionUpdate {
	return _u.SetModuleID(v.ID)
}

// Mutation returns the DimensionMutation object of the builder.
func (_u *DimensionUpdate) Mutation() *DimensionMutation {
	return _u.mutation
}

// ClearModule clears the "module" edge to the Module entity.
func (_u *DimensionUpdate) ClearModule() *DimensionUpdate {
	_u.mutation.ClearModule()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DimensionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DimensionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DimensionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DimensionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DimensionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dimension.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DimensionUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := dimension.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Dimension.title": %w`, err)}
		}
	}
	if _u.mutation.ModuleCleared() && len(_u.mutation.ModuleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Dimension.module"`)
	}
	return nil
}

func (_u *DimensionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dimension.Table, dimension.Columns, sqlgraph.NewFieldSpec(dimension.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(dimension.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(dimension.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Judgment(); ok {
		_spec.SetField(dimension.FieldJudgment, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedJudgment(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, dimension.FieldJudgment, value)
		})
	}
	if _u.mutation.JudgmentCleared() {
		_spec.ClearField(dimension.FieldJudgment, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dimension.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(dimension.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(dimension.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.ModuleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dimension.ModuleTable,
			Columns: []string{dimension.ModuleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(module.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ModuleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dimension.ModuleTable,
			Columns: []string{dimension.ModuleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(module.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dimension.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DimensionUpdateOne is the builder for updating a single Dimension entity.
type DimensionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DimensionMutation
}

// SetModuleID sets the "module_id" field.
func (_u *DimensionUpdateOne) SetModuleID(v int64) *DimensionUpdateOne {
	_u.mutation.SetModuleID(v)
	return _u
}

// SetNillableModuleID sets the "module_id" field if the given value is not nil.
func (_u *DimensionUpdateOne) SetNillableModuleID(v *int64) *DimensionUpdateOne {
	if v != nil {
		_u.SetModuleID(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *DimensionUpdateOne) SetDescription(v string) *DimensionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DimensionUpdateOne) SetNillableDescription(v *string) *DimensionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *DimensionUpdateOne) SetTitle(v string) *DimensionUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *DimensionUpdateOne) SetNillableTitle(v *string) *DimensionUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetJudgment sets the "judgment" field.
func (_u *DimensionUpdateOne) SetJudgment(v []map[string]interface{}) *DimensionUpdateOne {
	_u.mutation.SetJudgment(v)
	return _u
}

// AppendJudgment appends value to the "judgment" field.
func (_u *DimensionUpdateOne) AppendJudgment(v []map[string]interface{}) *DimensionUpdateOne {
	_u.mutation.AppendJudgment(v)
	return _u
}

// ClearJudgment clears the value of the "judgment" field.
func (_u *DimensionUpdateOne) ClearJudgment() *DimensionUpdateOne {
	_u.mutation.ClearJudgment()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DimensionUpdateOne) SetUpdatedAt(v time.Time) *DimensionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DimensionUpdateOne) SetDeletedAt(v time.Time) *DimensionUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DimensionUpdateOne) SetNillableDeletedAt(v *time.Time) *DimensionUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DimensionUpdateOne) ClearDeletedAt() *DimensionUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetModule sets the "module" edge to the Module entity.
func (_u *DimensionUpdateOne) SetModule(v *Module) *DimensionUpdateOne {
	return _u.SetModuleID(v.ID)
}

// Mutation returns the DimensionMutation object of the builder.
func (_u *DimensionUpdateOne) Mutation() *DimensionMutation {
	return _u.mutation
}

// ClearModule clears the "module" edge to the Module entity.
func (_u *DimensionUpdateOne) ClearModule() *DimensionUpdateOne {
	_u.mutation.ClearModule()
	return _u
}

// Where appends a list predicates to the DimensionUpdate builder.
func (_u *DimensionUpdateOne) Where(ps ...predicate.Dimension) *DimensionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DimensionUpdateOne) Select(field string, fields ...string) *DimensionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Dimension entity.
func (_u *DimensionUpdateOne) Save(ctx context.Context) (*Dimension, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DimensionUpdateOne) SaveX(ctx context.Context) *Dimension {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DimensionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DimensionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DimensionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dimension.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DimensionUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := dimension.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Dimension.title": %w`, err)}
		}
	}
	if _u.mutation.ModuleCleared() && len(_u.mutation.ModuleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Dimension.module"`)
	}
	return nil
}

func (_u *DimensionUpdateOne) sqlSave(ctx context.Context) (_node *Dimension, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dimension.Table, dimension.Columns, sqlgraph.NewFieldSpec(dimension.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Dimension.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dimension.FieldID)
		for _, f := range fields {
			if !dimension.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dimension.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(dimension.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(dimension.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Judgment(); ok {
		_spec.SetField(dimension.FieldJudgment, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedJudgment(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, dimension.FieldJudgment, value)
		})
	}
	if _u.mutation.JudgmentCleared() {
		_spec.ClearField(dimension.FieldJudgment, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dimension.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(dimension.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(dimension.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.ModuleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dimension.ModuleTable,
			Columns: []string{dimension.ModuleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(module.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ModuleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   dimension.ModuleTable,
			Columns: []string{dimension.ModuleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(module.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Dimension{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dimension.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
