// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cv2/internal/infra/ent/dimension"
	"cv2/internal/infra/ent/module"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Dimension is the model entity for the Dimension schema.
type Dimension struct {
	config `json:"-"`
	// ID of the ent.
	// 维度ID
	ID int64 `json:"id,omitempty"`
	// 所属模块ID
	ModuleID int64 `json:"module_id,omitempty"`
	// 描述
	Description string `json:"description,omitempty"`
	// 显示标题
	Title string `json:"title,omitempty"`
	// 维度得分详情（包括detail, score, weight的数组）
	Judgment []map[string]interface{} `json:"judgment,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DimensionQuery when eager-loading is set.
	Edges        DimensionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DimensionEdges holds the relations/edges for other nodes in the graph.
type DimensionEdges struct {
	// 所属模块
	Module *Module `json:"module,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ModuleOrErr returns the Module value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DimensionEdges) ModuleOrErr() (*Module, error) {
	if e.Module != nil {
		return e.Module, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: module.Label}
	}
	return nil, &NotLoadedError{edge: "module"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Dimension) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dimension.FieldJudgment:
			values[i] = new([]byte)
		case dimension.FieldID, dimension.FieldModuleID:
			values[i] = new(sql.NullInt64)
		case dimension.FieldDescription, dimension.FieldTitle:
			values[i] = new(sql.NullString)
		case dimension.FieldCreatedAt, dimension.FieldUpdatedAt, dimension.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Dimension fields.
func (_m *Dimension) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dimension.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case dimension.FieldModuleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field module_id", values[i])
			} else if value.Valid {
				_m.ModuleID = value.Int64
			}
		case dimension.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case dimension.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case dimension.FieldJudgment:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field judgment", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Judgment); err != nil {
					return fmt.Errorf("unmarshal field judgment: %w", err)
				}
			}
		case dimension.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case dimension.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case dimension.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Dimension.
// This includes values selected through modifiers, order, etc.
func (_m *Dimension) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryModule queries the "module" edge of the Dimension entity.
func (_m *Dimension) QueryModule() *ModuleQuery {
	return NewDimensionClient(_m.config).QueryModule(_m)
}

// Update returns a builder for updating this Dimension.
// Note that you need to call Dimension.Unwrap() before calling this method if this Dimension
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Dimension) Update() *DimensionUpdateOne {
	return NewDimensionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Dimension entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Dimension) Unwrap() *Dimension {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Dimension is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Dimension) String() string {
	var builder strings.Builder
	builder.WriteString("Dimension(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("module_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModuleID))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("judgment=")
	builder.WriteString(fmt.Sprintf("%v", _m.Judgment))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Dimensions is a parsable slice of Dimension.
type Dimensions []*Dimension
