// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cv2/internal/infra/ent/dimension"
	"cv2/internal/infra/ent/module"
	"cv2/internal/infra/ent/predicate"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ModuleUpdate is the builder for updating Module entities.
type ModuleUpdate struct {
	config
	hooks    []Hook
	mutation *ModuleMutation
}

// Where appends a list predicates to the ModuleUpdate builder.
func (_u *ModuleUpdate) Where(ps ...predicate.Module) *ModuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *ModuleUpdate) SetTitle(v string) *ModuleUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ModuleUpdate) SetNillableTitle(v *string) *ModuleUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ModuleUpdate) SetDescription(v string) *ModuleUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ModuleUpdate) SetNillableDescription(v *string) *ModuleUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModuleUpdate) SetUpdatedAt(v time.Time) *ModuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ModuleUpdate) SetDeletedAt(v time.Time) *ModuleUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ModuleUpdate) SetNillableDeletedAt(v *time.Time) *ModuleUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDimensionIDs adds the "dimensions" edge to the Dimension entity by IDs.
func (_u *ModuleUpdate) AddDimensionIDs(ids ...int64) *ModuleUpdate {
	_u.mutation.AddDimensionIDs(ids...)
	return _u
}

// AddDimensions adds the "dimensions" edges to the Dimension entity.
func (_u *ModuleUpdate) AddDimensions(v ...*Dimension) *ModuleUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDimensionIDs(ids...)
}

// Mutation returns the ModuleMutation object of the builder.
func (_u *ModuleUpdate) Mutation() *ModuleMutation {
	return _u.mutation
}

// ClearDimensions clears all "dimensions" edges to the Dimension entity.
func (_u *ModuleUpdate) ClearDimensions() *ModuleUpdate {
	_u.mutation.ClearDimensions()
	return _u
}

// RemoveDimensionIDs removes the "dimensions" edge to Dimension entities by IDs.
func (_u *ModuleUpdate) RemoveDimensionIDs(ids ...int64) *ModuleUpdate {
	_u.mutation.RemoveDimensionIDs(ids...)
	return _u
}

// RemoveDimensions removes "dimensions" edges to Dimension entities.
func (_u *ModuleUpdate) RemoveDimensions(v ...*Dimension) *ModuleUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDimensionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModuleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModuleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := module.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModuleUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := module.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Module.title": %w`, err)}
		}
	}
	return nil
}

func (_u *ModuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(module.Table, module.Columns, sqlgraph.NewFieldSpec(module.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(module.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(module.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(module.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(module.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DimensionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   module.DimensionsTable,
			Columns: []string{module.DimensionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dimension.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDimensionsIDs(); len(nodes) > 0 && !_u.mutation.DimensionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   module.DimensionsTable,
			Columns: []string{module.DimensionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dimension.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DimensionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   module.DimensionsTable,
			Columns: []string{module.DimensionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dimension.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{module.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModuleUpdateOne is the builder for updating a single Module entity.
type ModuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModuleMutation
}

// SetTitle sets the "title" field.
func (_u *ModuleUpdateOne) SetTitle(v string) *ModuleUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ModuleUpdateOne) SetNillableTitle(v *string) *ModuleUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ModuleUpdateOne) SetDescription(v string) *ModuleUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ModuleUpdateOne) SetNillableDescription(v *string) *ModuleUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModuleUpdateOne) SetUpdatedAt(v time.Time) *ModuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ModuleUpdateOne) SetDeletedAt(v time.Time) *ModuleUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ModuleUpdateOne) SetNillableDeletedAt(v *time.Time) *ModuleUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDimensionIDs adds the "dimensions" edge to the Dimension entity by IDs.
func (_u *ModuleUpdateOne) AddDimensionIDs(ids ...int64) *ModuleUpdateOne {
	_u.mutation.AddDimensionIDs(ids...)
	return _u
}

// AddDimensions adds the "dimensions" edges to the Dimension entity.
func (_u *ModuleUpdateOne) AddDimensions(v ...*Dimension) *ModuleUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDimensionIDs(ids...)
}

// Mutation returns the ModuleMutation object of the builder.
func (_u *ModuleUpdateOne) Mutation() *ModuleMutation {
	return _u.mutation
}

// ClearDimensions clears all "dimensions" edges to the Dimension entity.
func (_u *ModuleUpdateOne) ClearDimensions() *ModuleUpdateOne {
	_u.mutation.ClearDimensions()
	return _u
}

// RemoveDimensionIDs removes the "dimensions" edge to Dimension entities by IDs.
func (_u *ModuleUpdateOne) RemoveDimensionIDs(ids ...int64) *ModuleUpdateOne {
	_u.mutation.RemoveDimensionIDs(ids...)
	return _u
}

// RemoveDimensions removes "dimensions" edges to Dimension entities.
func (_u *ModuleUpdateOne) RemoveDimensions(v ...*Dimension) *ModuleUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDimensionIDs(ids...)
}

// Where appends a list predicates to the ModuleUpdate builder.
func (_u *ModuleUpdateOne) Where(ps ...predicate.Module) *ModuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModuleUpdateOne) Select(field string, fields ...string) *ModuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Module entity.
func (_u *ModuleUpdateOne) Save(ctx context.Context) (*Module, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModuleUpdateOne) SaveX(ctx context.Context) *Module {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModuleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := module.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModuleUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := module.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Module.title": %w`, err)}
		}
	}
	return nil
}

func (_u *ModuleUpdateOne) sqlSave(ctx context.Context) (_node *Module, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(module.Table, module.Columns, sqlgraph.NewFieldSpec(module.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Module.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, module.FieldID)
		for _, f := range fields {
			if !module.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != module.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(module.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(module.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(module.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(module.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DimensionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   module.DimensionsTable,
			Columns: []string{module.DimensionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dimension.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDimensionsIDs(); len(nodes) > 0 && !_u.mutation.DimensionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   module.DimensionsTable,
			Columns: []string{module.DimensionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dimension.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DimensionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   module.DimensionsTable,
			Columns: []string{module.DimensionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dimension.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Module{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{module.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
