// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cv2/internal/infra/ent/predicate"
	"cv2/internal/infra/ent/resume"
	"cv2/internal/infra/ent/resumescore"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ResumeQuery is the builder for querying Resume entities.
type ResumeQuery struct {
	config
	ctx        *QueryContext
	order      []resume.OrderOption
	inters     []Interceptor
	predicates []predicate.Resume
	withScores *ResumeScoreQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ResumeQuery builder.
func (_q *ResumeQuery) Where(ps ...predicate.Resume) *ResumeQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ResumeQuery) Limit(limit int) *ResumeQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ResumeQuery) Offset(offset int) *ResumeQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ResumeQuery) Unique(unique bool) *ResumeQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ResumeQuery) Order(o ...resume.OrderOption) *ResumeQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryScores chains the current query on the "scores" edge.
func (_q *ResumeQuery) QueryScores() *ResumeScoreQuery {
	query := (&ResumeScoreClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(resume.Table, resume.FieldID, selector),
			sqlgraph.To(resumescore.Table, resumescore.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, resume.ScoresTable, resume.ScoresColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Resume entity from the query.
// Returns a *NotFoundError when no Resume was found.
func (_q *ResumeQuery) First(ctx context.Context) (*Resume, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{resume.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ResumeQuery) FirstX(ctx context.Context) *Resume {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Resume ID from the query.
// Returns a *NotFoundError when no Resume ID was found.
func (_q *ResumeQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{resume.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ResumeQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Resume entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Resume entity is found.
// Returns a *NotFoundError when no Resume entities are found.
func (_q *ResumeQuery) Only(ctx context.Context) (*Resume, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{resume.Label}
	default:
		return nil, &NotSingularError{resume.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ResumeQuery) OnlyX(ctx context.Context) *Resume {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Resume ID in the query.
// Returns a *NotSingularError when more than one Resume ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ResumeQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{resume.Label}
	default:
		err = &NotSingularError{resume.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ResumeQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Resumes.
func (_q *ResumeQuery) All(ctx context.Context) ([]*Resume, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Resume, *ResumeQuery]()
	return withInterceptors[[]*Resume](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ResumeQuery) AllX(ctx context.Context) []*Resume {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Resume IDs.
func (_q *ResumeQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(resume.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ResumeQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ResumeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ResumeQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ResumeQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ResumeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ResumeQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ResumeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ResumeQuery) Clone() *ResumeQuery {
	if _q == nil {
		return nil
	}
	return &ResumeQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]resume.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.Resume{}, _q.predicates...),
		withScores: _q.withScores.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithScores tells the query-builder to eager-load the nodes that are connected to
// the "scores" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ResumeQuery) WithScores(opts ...func(*ResumeScoreQuery)) *ResumeQuery {
	query := (&ResumeScoreClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withScores = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int64 `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Resume.Query().
//		GroupBy(resume.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ResumeQuery) GroupBy(field string, fields ...string) *ResumeGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ResumeGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = resume.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int64 `json:"user_id,omitempty"`
//	}
//
//	client.Resume.Query().
//		Select(resume.FieldUserID).
//		Scan(ctx, &v)
func (_q *ResumeQuery) Select(fields ...string) *ResumeSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ResumeSelect{ResumeQuery: _q}
	sbuild.label = resume.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ResumeSelect configured with the given aggregations.
func (_q *ResumeQuery) Aggregate(fns ...AggregateFunc) *ResumeSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ResumeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !resume.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ResumeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Resume, error) {
	var (
		nodes       = []*Resume{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withScores != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Resume).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Resume{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withScores; query != nil {
		if err := _q.loadScores(ctx, query, nodes,
			func(n *Resume) { n.Edges.Scores = []*ResumeScore{} },
			func(n *Resume, e *ResumeScore) { n.Edges.Scores = append(n.Edges.Scores, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ResumeQuery) loadScores(ctx context.Context, query *ResumeScoreQuery, nodes []*Resume, init func(*Resume), assign func(*Resume, *ResumeScore)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*Resume)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(resumescore.FieldResumeID)
	}
	query.Where(predicate.ResumeScore(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(resume.ScoresColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ResumeID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "resume_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ResumeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ResumeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(resume.Table, resume.Columns, sqlgraph.NewFieldSpec(resume.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resume.FieldID)
		for i := range fields {
			if fields[i] != resume.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ResumeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(resume.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = resume.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ResumeGroupBy is the group-by builder for Resume entities.
type ResumeGroupBy struct {
	selector
	build *ResumeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ResumeGroupBy) Aggregate(fns ...AggregateFunc) *ResumeGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ResumeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ResumeQuery, *ResumeGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ResumeGroupBy) sqlScan(ctx context.Context, root *ResumeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ResumeSelect is the builder for selecting fields of Resume entities.
type ResumeSelect struct {
	*ResumeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ResumeSelect) Aggregate(fns ...AggregateFunc) *ResumeSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ResumeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ResumeQuery, *ResumeSelect](ctx, _s.ResumeQuery, _s, _s.inters, v)
}

func (_s *ResumeSelect) sqlScan(ctx context.Context, root *ResumeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
