// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cv2/internal/infra/ent/resumeslot"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ResumeSlot is the model entity for the ResumeSlot schema.
type ResumeSlot struct {
	config `json:"-"`
	// ID of the ent.
	// 主键ID
	ID int64 `json:"id,omitempty"`
	// 用户ID
	UserID string `json:"user_id,omitempty"`
	// 最大席位数量
	MaxSlots int32 `json:"max_slots,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt    *time.Time `json:"deleted_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ResumeSlot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case resumeslot.FieldID, resumeslot.FieldMaxSlots:
			values[i] = new(sql.NullInt64)
		case resumeslot.FieldUserID:
			values[i] = new(sql.NullString)
		case resumeslot.FieldCreatedAt, resumeslot.FieldUpdatedAt, resumeslot.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ResumeSlot fields.
func (_m *ResumeSlot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case resumeslot.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case resumeslot.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case resumeslot.FieldMaxSlots:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_slots", values[i])
			} else if value.Valid {
				_m.MaxSlots = int32(value.Int64)
			}
		case resumeslot.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case resumeslot.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case resumeslot.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ResumeSlot.
// This includes values selected through modifiers, order, etc.
func (_m *ResumeSlot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ResumeSlot.
// Note that you need to call ResumeSlot.Unwrap() before calling this method if this ResumeSlot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ResumeSlot) Update() *ResumeSlotUpdateOne {
	return NewResumeSlotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ResumeSlot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ResumeSlot) Unwrap() *ResumeSlot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ResumeSlot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ResumeSlot) String() string {
	var builder strings.Builder
	builder.WriteString("ResumeSlot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("max_slots=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxSlots))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ResumeSlots is a parsable slice of ResumeSlot.
type ResumeSlots []*ResumeSlot
