// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cv2/internal/infra/ent/predicate"
	"cv2/internal/infra/ent/resumeslot"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ResumeSlotUpdate is the builder for updating ResumeSlot entities.
type ResumeSlotUpdate struct {
	config
	hooks    []Hook
	mutation *ResumeSlotMutation
}

// Where appends a list predicates to the ResumeSlotUpdate builder.
func (_u *ResumeSlotUpdate) Where(ps ...predicate.ResumeSlot) *ResumeSlotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ResumeSlotUpdate) SetUserID(v string) *ResumeSlotUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ResumeSlotUpdate) SetNillableUserID(v *string) *ResumeSlotUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetMaxSlots sets the "max_slots" field.
func (_u *ResumeSlotUpdate) SetMaxSlots(v int32) *ResumeSlotUpdate {
	_u.mutation.ResetMaxSlots()
	_u.mutation.SetMaxSlots(v)
	return _u
}

// SetNillableMaxSlots sets the "max_slots" field if the given value is not nil.
func (_u *ResumeSlotUpdate) SetNillableMaxSlots(v *int32) *ResumeSlotUpdate {
	if v != nil {
		_u.SetMaxSlots(*v)
	}
	return _u
}

// AddMaxSlots adds value to the "max_slots" field.
func (_u *ResumeSlotUpdate) AddMaxSlots(v int32) *ResumeSlotUpdate {
	_u.mutation.AddMaxSlots(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResumeSlotUpdate) SetUpdatedAt(v time.Time) *ResumeSlotUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ResumeSlotUpdate) SetDeletedAt(v time.Time) *ResumeSlotUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ResumeSlotUpdate) SetNillableDeletedAt(v *time.Time) *ResumeSlotUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ResumeSlotUpdate) ClearDeletedAt() *ResumeSlotUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the ResumeSlotMutation object of the builder.
func (_u *ResumeSlotUpdate) Mutation() *ResumeSlotMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ResumeSlotUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResumeSlotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ResumeSlotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResumeSlotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResumeSlotUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := resumeslot.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResumeSlotUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := resumeslot.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "ResumeSlot.user_id": %w`, err)}
		}
	}
	return nil
}

func (_u *ResumeSlotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resumeslot.Table, resumeslot.Columns, sqlgraph.NewFieldSpec(resumeslot.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(resumeslot.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxSlots(); ok {
		_spec.SetField(resumeslot.FieldMaxSlots, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedMaxSlots(); ok {
		_spec.AddField(resumeslot.FieldMaxSlots, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resumeslot.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(resumeslot.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(resumeslot.FieldDeletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resumeslot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ResumeSlotUpdateOne is the builder for updating a single ResumeSlot entity.
type ResumeSlotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ResumeSlotMutation
}

// SetUserID sets the "user_id" field.
func (_u *ResumeSlotUpdateOne) SetUserID(v string) *ResumeSlotUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ResumeSlotUpdateOne) SetNillableUserID(v *string) *ResumeSlotUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetMaxSlots sets the "max_slots" field.
func (_u *ResumeSlotUpdateOne) SetMaxSlots(v int32) *ResumeSlotUpdateOne {
	_u.mutation.ResetMaxSlots()
	_u.mutation.SetMaxSlots(v)
	return _u
}

// SetNillableMaxSlots sets the "max_slots" field if the given value is not nil.
func (_u *ResumeSlotUpdateOne) SetNillableMaxSlots(v *int32) *ResumeSlotUpdateOne {
	if v != nil {
		_u.SetMaxSlots(*v)
	}
	return _u
}

// AddMaxSlots adds value to the "max_slots" field.
func (_u *ResumeSlotUpdateOne) AddMaxSlots(v int32) *ResumeSlotUpdateOne {
	_u.mutation.AddMaxSlots(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResumeSlotUpdateOne) SetUpdatedAt(v time.Time) *ResumeSlotUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ResumeSlotUpdateOne) SetDeletedAt(v time.Time) *ResumeSlotUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ResumeSlotUpdateOne) SetNillableDeletedAt(v *time.Time) *ResumeSlotUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ResumeSlotUpdateOne) ClearDeletedAt() *ResumeSlotUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the ResumeSlotMutation object of the builder.
func (_u *ResumeSlotUpdateOne) Mutation() *ResumeSlotMutation {
	return _u.mutation
}

// Where appends a list predicates to the ResumeSlotUpdate builder.
func (_u *ResumeSlotUpdateOne) Where(ps ...predicate.ResumeSlot) *ResumeSlotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ResumeSlotUpdateOne) Select(field string, fields ...string) *ResumeSlotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ResumeSlot entity.
func (_u *ResumeSlotUpdateOne) Save(ctx context.Context) (*ResumeSlot, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResumeSlotUpdateOne) SaveX(ctx context.Context) *ResumeSlot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ResumeSlotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResumeSlotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResumeSlotUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := resumeslot.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResumeSlotUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := resumeslot.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "ResumeSlot.user_id": %w`, err)}
		}
	}
	return nil
}

func (_u *ResumeSlotUpdateOne) sqlSave(ctx context.Context) (_node *ResumeSlot, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resumeslot.Table, resumeslot.Columns, sqlgraph.NewFieldSpec(resumeslot.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ResumeSlot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resumeslot.FieldID)
		for _, f := range fields {
			if !resumeslot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != resumeslot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(resumeslot.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxSlots(); ok {
		_spec.SetField(resumeslot.FieldMaxSlots, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedMaxSlots(); ok {
		_spec.AddField(resumeslot.FieldMaxSlots, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resumeslot.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(resumeslot.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(resumeslot.FieldDeletedAt, field.TypeTime)
	}
	_node = &ResumeSlot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resumeslot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
