// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cv2/internal/infra/ent/resume"
	"cv2/internal/infra/ent/resumescore"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ResumeScore is the model entity for the ResumeScore schema.
type ResumeScore struct {
	config `json:"-"`
	// ID of the ent.
	// 得分ID
	ID int64 `json:"id,omitempty"`
	// 关联简历ID
	ResumeID int64 `json:"resume_id,omitempty"`
	// 关联的模块ID或维度ID
	TargetID int64 `json:"target_id,omitempty"`
	// 类型: 0=module, 1=dimension
	TargetType int32 `json:"target_type,omitempty"`
	// 得分
	Score float64 `json:"score,omitempty"`
	// 权重
	Weight float64 `json:"weight,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ResumeScoreQuery when eager-loading is set.
	Edges        ResumeScoreEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ResumeScoreEdges holds the relations/edges for other nodes in the graph.
type ResumeScoreEdges struct {
	// 关联简历
	Resume *Resume `json:"resume,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ResumeOrErr returns the Resume value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ResumeScoreEdges) ResumeOrErr() (*Resume, error) {
	if e.Resume != nil {
		return e.Resume, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: resume.Label}
	}
	return nil, &NotLoadedError{edge: "resume"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ResumeScore) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case resumescore.FieldScore, resumescore.FieldWeight:
			values[i] = new(sql.NullFloat64)
		case resumescore.FieldID, resumescore.FieldResumeID, resumescore.FieldTargetID, resumescore.FieldTargetType:
			values[i] = new(sql.NullInt64)
		case resumescore.FieldCreatedAt, resumescore.FieldUpdatedAt, resumescore.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ResumeScore fields.
func (_m *ResumeScore) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case resumescore.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case resumescore.FieldResumeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field resume_id", values[i])
			} else if value.Valid {
				_m.ResumeID = value.Int64
			}
		case resumescore.FieldTargetID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field target_id", values[i])
			} else if value.Valid {
				_m.TargetID = value.Int64
			}
		case resumescore.FieldTargetType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field target_type", values[i])
			} else if value.Valid {
				_m.TargetType = int32(value.Int64)
			}
		case resumescore.FieldScore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field score", values[i])
			} else if value.Valid {
				_m.Score = value.Float64
			}
		case resumescore.FieldWeight:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field weight", values[i])
			} else if value.Valid {
				_m.Weight = value.Float64
			}
		case resumescore.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case resumescore.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case resumescore.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ResumeScore.
// This includes values selected through modifiers, order, etc.
func (_m *ResumeScore) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryResume queries the "resume" edge of the ResumeScore entity.
func (_m *ResumeScore) QueryResume() *ResumeQuery {
	return NewResumeScoreClient(_m.config).QueryResume(_m)
}

// Update returns a builder for updating this ResumeScore.
// Note that you need to call ResumeScore.Unwrap() before calling this method if this ResumeScore
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ResumeScore) Update() *ResumeScoreUpdateOne {
	return NewResumeScoreClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ResumeScore entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ResumeScore) Unwrap() *ResumeScore {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ResumeScore is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ResumeScore) String() string {
	var builder strings.Builder
	builder.WriteString("ResumeScore(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("resume_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResumeID))
	builder.WriteString(", ")
	builder.WriteString("target_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetID))
	builder.WriteString(", ")
	builder.WriteString("target_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetType))
	builder.WriteString(", ")
	builder.WriteString("score=")
	builder.WriteString(fmt.Sprintf("%v", _m.Score))
	builder.WriteString(", ")
	builder.WriteString("weight=")
	builder.WriteString(fmt.Sprintf("%v", _m.Weight))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ResumeScores is a parsable slice of ResumeScore.
type ResumeScores []*ResumeScore
