// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cv2/internal/infra/ent/predicate"
	"cv2/internal/infra/ent/resume"
	"cv2/internal/infra/ent/resumescore"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ResumeScoreUpdate is the builder for updating ResumeScore entities.
type ResumeScoreUpdate struct {
	config
	hooks    []Hook
	mutation *ResumeScoreMutation
}

// Where appends a list predicates to the ResumeScoreUpdate builder.
func (_u *ResumeScoreUpdate) Where(ps ...predicate.ResumeScore) *ResumeScoreUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetResumeID sets the "resume_id" field.
func (_u *ResumeScoreUpdate) SetResumeID(v int64) *ResumeScoreUpdate {
	_u.mutation.SetResumeID(v)
	return _u
}

// SetNillableResumeID sets the "resume_id" field if the given value is not nil.
func (_u *ResumeScoreUpdate) SetNillableResumeID(v *int64) *ResumeScoreUpdate {
	if v != nil {
		_u.SetResumeID(*v)
	}
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *ResumeScoreUpdate) SetTargetID(v int64) *ResumeScoreUpdate {
	_u.mutation.ResetTargetID()
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *ResumeScoreUpdate) SetNillableTargetID(v *int64) *ResumeScoreUpdate {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// AddTargetID adds value to the "target_id" field.
func (_u *ResumeScoreUpdate) AddTargetID(v int64) *ResumeScoreUpdate {
	_u.mutation.AddTargetID(v)
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *ResumeScoreUpdate) SetTargetType(v int32) *ResumeScoreUpdate {
	_u.mutation.ResetTargetType()
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *ResumeScoreUpdate) SetNillableTargetType(v *int32) *ResumeScoreUpdate {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// AddTargetType adds value to the "target_type" field.
func (_u *ResumeScoreUpdate) AddTargetType(v int32) *ResumeScoreUpdate {
	_u.mutation.AddTargetType(v)
	return _u
}

// SetScore sets the "score" field.
func (_u *ResumeScoreUpdate) SetScore(v float64) *ResumeScoreUpdate {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *ResumeScoreUpdate) SetNillableScore(v *float64) *ResumeScoreUpdate {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *ResumeScoreUpdate) AddScore(v float64) *ResumeScoreUpdate {
	_u.mutation.AddScore(v)
	return _u
}

// SetWeight sets the "weight" field.
func (_u *ResumeScoreUpdate) SetWeight(v float64) *ResumeScoreUpdate {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *ResumeScoreUpdate) SetNillableWeight(v *float64) *ResumeScoreUpdate {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *ResumeScoreUpdate) AddWeight(v float64) *ResumeScoreUpdate {
	_u.mutation.AddWeight(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResumeScoreUpdate) SetUpdatedAt(v time.Time) *ResumeScoreUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ResumeScoreUpdate) SetDeletedAt(v time.Time) *ResumeScoreUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ResumeScoreUpdate) SetNillableDeletedAt(v *time.Time) *ResumeScoreUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ResumeScoreUpdate) ClearDeletedAt() *ResumeScoreUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetResume sets the "resume" edge to the Resume entity.
func (_u *ResumeScoreUpdate) SetResume(v *Resume) *ResumeScoreUpdate {
	return _u.SetResumeID(v.ID)
}

// Mutation returns the ResumeScoreMutation object of the builder.
func (_u *ResumeScoreUpdate) Mutation() *ResumeScoreMutation {
	return _u.mutation
}

// ClearResume clears the "resume" edge to the Resume entity.
func (_u *ResumeScoreUpdate) ClearResume() *ResumeScoreUpdate {
	_u.mutation.ClearResume()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ResumeScoreUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResumeScoreUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ResumeScoreUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResumeScoreUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResumeScoreUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := resumescore.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResumeScoreUpdate) check() error {
	if _u.mutation.ResumeCleared() && len(_u.mutation.ResumeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ResumeScore.resume"`)
	}
	return nil
}

func (_u *ResumeScoreUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resumescore.Table, resumescore.Columns, sqlgraph.NewFieldSpec(resumescore.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(resumescore.FieldTargetID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTargetID(); ok {
		_spec.AddField(resumescore.FieldTargetID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(resumescore.FieldTargetType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedTargetType(); ok {
		_spec.AddField(resumescore.FieldTargetType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(resumescore.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(resumescore.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(resumescore.FieldWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(resumescore.FieldWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resumescore.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(resumescore.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(resumescore.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.ResumeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resumescore.ResumeTable,
			Columns: []string{resumescore.ResumeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resume.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResumeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resumescore.ResumeTable,
			Columns: []string{resumescore.ResumeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resume.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resumescore.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ResumeScoreUpdateOne is the builder for updating a single ResumeScore entity.
type ResumeScoreUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ResumeScoreMutation
}

// SetResumeID sets the "resume_id" field.
func (_u *ResumeScoreUpdateOne) SetResumeID(v int64) *ResumeScoreUpdateOne {
	_u.mutation.SetResumeID(v)
	return _u
}

// SetNillableResumeID sets the "resume_id" field if the given value is not nil.
func (_u *ResumeScoreUpdateOne) SetNillableResumeID(v *int64) *ResumeScoreUpdateOne {
	if v != nil {
		_u.SetResumeID(*v)
	}
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *ResumeScoreUpdateOne) SetTargetID(v int64) *ResumeScoreUpdateOne {
	_u.mutation.ResetTargetID()
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *ResumeScoreUpdateOne) SetNillableTargetID(v *int64) *ResumeScoreUpdateOne {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// AddTargetID adds value to the "target_id" field.
func (_u *ResumeScoreUpdateOne) AddTargetID(v int64) *ResumeScoreUpdateOne {
	_u.mutation.AddTargetID(v)
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *ResumeScoreUpdateOne) SetTargetType(v int32) *ResumeScoreUpdateOne {
	_u.mutation.ResetTargetType()
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *ResumeScoreUpdateOne) SetNillableTargetType(v *int32) *ResumeScoreUpdateOne {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// AddTargetType adds value to the "target_type" field.
func (_u *ResumeScoreUpdateOne) AddTargetType(v int32) *ResumeScoreUpdateOne {
	_u.mutation.AddTargetType(v)
	return _u
}

// SetScore sets the "score" field.
func (_u *ResumeScoreUpdateOne) SetScore(v float64) *ResumeScoreUpdateOne {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *ResumeScoreUpdateOne) SetNillableScore(v *float64) *ResumeScoreUpdateOne {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *ResumeScoreUpdateOne) AddScore(v float64) *ResumeScoreUpdateOne {
	_u.mutation.AddScore(v)
	return _u
}

// SetWeight sets the "weight" field.
func (_u *ResumeScoreUpdateOne) SetWeight(v float64) *ResumeScoreUpdateOne {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *ResumeScoreUpdateOne) SetNillableWeight(v *float64) *ResumeScoreUpdateOne {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *ResumeScoreUpdateOne) AddWeight(v float64) *ResumeScoreUpdateOne {
	_u.mutation.AddWeight(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResumeScoreUpdateOne) SetUpdatedAt(v time.Time) *ResumeScoreUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ResumeScoreUpdateOne) SetDeletedAt(v time.Time) *ResumeScoreUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ResumeScoreUpdateOne) SetNillableDeletedAt(v *time.Time) *ResumeScoreUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ResumeScoreUpdateOne) ClearDeletedAt() *ResumeScoreUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetResume sets the "resume" edge to the Resume entity.
func (_u *ResumeScoreUpdateOne) SetResume(v *Resume) *ResumeScoreUpdateOne {
	return _u.SetResumeID(v.ID)
}

// Mutation returns the ResumeScoreMutation object of the builder.
func (_u *ResumeScoreUpdateOne) Mutation() *ResumeScoreMutation {
	return _u.mutation
}

// ClearResume clears the "resume" edge to the Resume entity.
func (_u *ResumeScoreUpdateOne) ClearResume() *ResumeScoreUpdateOne {
	_u.mutation.ClearResume()
	return _u
}

// Where appends a list predicates to the ResumeScoreUpdate builder.
func (_u *ResumeScoreUpdateOne) Where(ps ...predicate.ResumeScore) *ResumeScoreUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ResumeScoreUpdateOne) Select(field string, fields ...string) *ResumeScoreUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ResumeScore entity.
func (_u *ResumeScoreUpdateOne) Save(ctx context.Context) (*ResumeScore, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResumeScoreUpdateOne) SaveX(ctx context.Context) *ResumeScore {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ResumeScoreUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResumeScoreUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResumeScoreUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := resumescore.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResumeScoreUpdateOne) check() error {
	if _u.mutation.ResumeCleared() && len(_u.mutation.ResumeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ResumeScore.resume"`)
	}
	return nil
}

func (_u *ResumeScoreUpdateOne) sqlSave(ctx context.Context) (_node *ResumeScore, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resumescore.Table, resumescore.Columns, sqlgraph.NewFieldSpec(resumescore.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ResumeScore.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resumescore.FieldID)
		for _, f := range fields {
			if !resumescore.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != resumescore.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(resumescore.FieldTargetID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTargetID(); ok {
		_spec.AddField(resumescore.FieldTargetID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(resumescore.FieldTargetType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedTargetType(); ok {
		_spec.AddField(resumescore.FieldTargetType, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(resumescore.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(resumescore.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(resumescore.FieldWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(resumescore.FieldWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resumescore.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(resumescore.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(resumescore.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.ResumeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resumescore.ResumeTable,
			Columns: []string{resumescore.ResumeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resume.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResumeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resumescore.ResumeTable,
			Columns: []string{resumescore.ResumeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resume.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ResumeScore{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resumescore.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
