// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cv2/internal/infra/ent/predicate"
	"cv2/internal/infra/ent/resume"
	"cv2/internal/infra/ent/resumescore"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ResumeUpdate is the builder for updating Resume entities.
type ResumeUpdate struct {
	config
	hooks    []Hook
	mutation *ResumeMutation
}

// Where appends a list predicates to the ResumeUpdate builder.
func (_u *ResumeUpdate) Where(ps ...predicate.Resume) *ResumeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ResumeUpdate) SetUserID(v int64) *ResumeUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ResumeUpdate) SetNillableUserID(v *int64) *ResumeUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ResumeUpdate) AddUserID(v int64) *ResumeUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ResumeUpdate) SetTenantID(v int64) *ResumeUpdate {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ResumeUpdate) SetNillableTenantID(v *int64) *ResumeUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *ResumeUpdate) AddTenantID(v int64) *ResumeUpdate {
	_u.mutation.AddTenantID(v)
	return _u
}

// SetFilePath sets the "file_path" field.
func (_u *ResumeUpdate) SetFilePath(v string) *ResumeUpdate {
	_u.mutation.SetFilePath(v)
	return _u
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_u *ResumeUpdate) SetNillableFilePath(v *string) *ResumeUpdate {
	if v != nil {
		_u.SetFilePath(*v)
	}
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *ResumeUpdate) SetFileName(v string) *ResumeUpdate {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *ResumeUpdate) SetNillableFileName(v *string) *ResumeUpdate {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ResumeUpdate) SetStatus(v int32) *ResumeUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ResumeUpdate) SetNillableStatus(v *int32) *ResumeUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *ResumeUpdate) AddStatus(v int32) *ResumeUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResumeUpdate) SetUpdatedAt(v time.Time) *ResumeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ResumeUpdate) SetDeletedAt(v time.Time) *ResumeUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ResumeUpdate) SetNillableDeletedAt(v *time.Time) *ResumeUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddScoreIDs adds the "scores" edge to the ResumeScore entity by IDs.
func (_u *ResumeUpdate) AddScoreIDs(ids ...int64) *ResumeUpdate {
	_u.mutation.AddScoreIDs(ids...)
	return _u
}

// AddScores adds the "scores" edges to the ResumeScore entity.
func (_u *ResumeUpdate) AddScores(v ...*ResumeScore) *ResumeUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddScoreIDs(ids...)
}

// Mutation returns the ResumeMutation object of the builder.
func (_u *ResumeUpdate) Mutation() *ResumeMutation {
	return _u.mutation
}

// ClearScores clears all "scores" edges to the ResumeScore entity.
func (_u *ResumeUpdate) ClearScores() *ResumeUpdate {
	_u.mutation.ClearScores()
	return _u
}

// RemoveScoreIDs removes the "scores" edge to ResumeScore entities by IDs.
func (_u *ResumeUpdate) RemoveScoreIDs(ids ...int64) *ResumeUpdate {
	_u.mutation.RemoveScoreIDs(ids...)
	return _u
}

// RemoveScores removes "scores" edges to ResumeScore entities.
func (_u *ResumeUpdate) RemoveScores(v ...*ResumeScore) *ResumeUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveScoreIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ResumeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResumeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ResumeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResumeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResumeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := resume.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResumeUpdate) check() error {
	if v, ok := _u.mutation.FilePath(); ok {
		if err := resume.FilePathValidator(v); err != nil {
			return &ValidationError{Name: "file_path", err: fmt.Errorf(`ent: validator failed for field "Resume.file_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := resume.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "Resume.file_name": %w`, err)}
		}
	}
	return nil
}

func (_u *ResumeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resume.Table, resume.Columns, sqlgraph.NewFieldSpec(resume.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(resume.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(resume.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(resume.FieldTenantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(resume.FieldTenantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FilePath(); ok {
		_spec.SetField(resume.FieldFilePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(resume.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(resume.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(resume.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resume.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(resume.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.ScoresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resume.ScoresTable,
			Columns: []string{resume.ScoresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resumescore.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedScoresIDs(); len(nodes) > 0 && !_u.mutation.ScoresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resume.ScoresTable,
			Columns: []string{resume.ScoresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resumescore.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ScoresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resume.ScoresTable,
			Columns: []string{resume.ScoresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resumescore.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resume.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ResumeUpdateOne is the builder for updating a single Resume entity.
type ResumeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ResumeMutation
}

// SetUserID sets the "user_id" field.
func (_u *ResumeUpdateOne) SetUserID(v int64) *ResumeUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ResumeUpdateOne) SetNillableUserID(v *int64) *ResumeUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *ResumeUpdateOne) AddUserID(v int64) *ResumeUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ResumeUpdateOne) SetTenantID(v int64) *ResumeUpdateOne {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ResumeUpdateOne) SetNillableTenantID(v *int64) *ResumeUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *ResumeUpdateOne) AddTenantID(v int64) *ResumeUpdateOne {
	_u.mutation.AddTenantID(v)
	return _u
}

// SetFilePath sets the "file_path" field.
func (_u *ResumeUpdateOne) SetFilePath(v string) *ResumeUpdateOne {
	_u.mutation.SetFilePath(v)
	return _u
}

// SetNillableFilePath sets the "file_path" field if the given value is not nil.
func (_u *ResumeUpdateOne) SetNillableFilePath(v *string) *ResumeUpdateOne {
	if v != nil {
		_u.SetFilePath(*v)
	}
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *ResumeUpdateOne) SetFileName(v string) *ResumeUpdateOne {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *ResumeUpdateOne) SetNillableFileName(v *string) *ResumeUpdateOne {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ResumeUpdateOne) SetStatus(v int32) *ResumeUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ResumeUpdateOne) SetNillableStatus(v *int32) *ResumeUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *ResumeUpdateOne) AddStatus(v int32) *ResumeUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ResumeUpdateOne) SetUpdatedAt(v time.Time) *ResumeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ResumeUpdateOne) SetDeletedAt(v time.Time) *ResumeUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ResumeUpdateOne) SetNillableDeletedAt(v *time.Time) *ResumeUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddScoreIDs adds the "scores" edge to the ResumeScore entity by IDs.
func (_u *ResumeUpdateOne) AddScoreIDs(ids ...int64) *ResumeUpdateOne {
	_u.mutation.AddScoreIDs(ids...)
	return _u
}

// AddScores adds the "scores" edges to the ResumeScore entity.
func (_u *ResumeUpdateOne) AddScores(v ...*ResumeScore) *ResumeUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddScoreIDs(ids...)
}

// Mutation returns the ResumeMutation object of the builder.
func (_u *ResumeUpdateOne) Mutation() *ResumeMutation {
	return _u.mutation
}

// ClearScores clears all "scores" edges to the ResumeScore entity.
func (_u *ResumeUpdateOne) ClearScores() *ResumeUpdateOne {
	_u.mutation.ClearScores()
	return _u
}

// RemoveScoreIDs removes the "scores" edge to ResumeScore entities by IDs.
func (_u *ResumeUpdateOne) RemoveScoreIDs(ids ...int64) *ResumeUpdateOne {
	_u.mutation.RemoveScoreIDs(ids...)
	return _u
}

// RemoveScores removes "scores" edges to ResumeScore entities.
func (_u *ResumeUpdateOne) RemoveScores(v ...*ResumeScore) *ResumeUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveScoreIDs(ids...)
}

// Where appends a list predicates to the ResumeUpdate builder.
func (_u *ResumeUpdateOne) Where(ps ...predicate.Resume) *ResumeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ResumeUpdateOne) Select(field string, fields ...string) *ResumeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Resume entity.
func (_u *ResumeUpdateOne) Save(ctx context.Context) (*Resume, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ResumeUpdateOne) SaveX(ctx context.Context) *Resume {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ResumeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ResumeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ResumeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := resume.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ResumeUpdateOne) check() error {
	if v, ok := _u.mutation.FilePath(); ok {
		if err := resume.FilePathValidator(v); err != nil {
			return &ValidationError{Name: "file_path", err: fmt.Errorf(`ent: validator failed for field "Resume.file_path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := resume.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "Resume.file_name": %w`, err)}
		}
	}
	return nil
}

func (_u *ResumeUpdateOne) sqlSave(ctx context.Context) (_node *Resume, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resume.Table, resume.Columns, sqlgraph.NewFieldSpec(resume.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Resume.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resume.FieldID)
		for _, f := range fields {
			if !resume.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != resume.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(resume.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(resume.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(resume.FieldTenantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(resume.FieldTenantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.FilePath(); ok {
		_spec.SetField(resume.FieldFilePath, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(resume.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(resume.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(resume.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(resume.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(resume.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.ScoresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resume.ScoresTable,
			Columns: []string{resume.ScoresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resumescore.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedScoresIDs(); len(nodes) > 0 && !_u.mutation.ScoresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resume.ScoresTable,
			Columns: []string{resume.ScoresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resumescore.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ScoresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resume.ScoresTable,
			Columns: []string{resume.ScoresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resumescore.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Resume{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resume.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
