// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cv2/internal/infra/ent/resume"
	"cv2/internal/infra/ent/resumescore"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ResumeScoreCreate is the builder for creating a ResumeScore entity.
type ResumeScoreCreate struct {
	config
	mutation *ResumeScoreMutation
	hooks    []Hook
}

// SetResumeID sets the "resume_id" field.
func (_c *ResumeScoreCreate) SetResumeID(v int64) *ResumeScoreCreate {
	_c.mutation.SetResumeID(v)
	return _c
}

// SetTargetID sets the "target_id" field.
func (_c *ResumeScoreCreate) SetTargetID(v int64) *ResumeScoreCreate {
	_c.mutation.SetTargetID(v)
	return _c
}

// SetTargetType sets the "target_type" field.
func (_c *ResumeScoreCreate) SetTargetType(v int32) *ResumeScoreCreate {
	_c.mutation.SetTargetType(v)
	return _c
}

// SetScore sets the "score" field.
func (_c *ResumeScoreCreate) SetScore(v float64) *ResumeScoreCreate {
	_c.mutation.SetScore(v)
	return _c
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_c *ResumeScoreCreate) SetNillableScore(v *float64) *ResumeScoreCreate {
	if v != nil {
		_c.SetScore(*v)
	}
	return _c
}

// SetWeight sets the "weight" field.
func (_c *ResumeScoreCreate) SetWeight(v float64) *ResumeScoreCreate {
	_c.mutation.SetWeight(v)
	return _c
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_c *ResumeScoreCreate) SetNillableWeight(v *float64) *ResumeScoreCreate {
	if v != nil {
		_c.SetWeight(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ResumeScoreCreate) SetCreatedAt(v time.Time) *ResumeScoreCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ResumeScoreCreate) SetNillableCreatedAt(v *time.Time) *ResumeScoreCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ResumeScoreCreate) SetUpdatedAt(v time.Time) *ResumeScoreCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ResumeScoreCreate) SetNillableUpdatedAt(v *time.Time) *ResumeScoreCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ResumeScoreCreate) SetDeletedAt(v time.Time) *ResumeScoreCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ResumeScoreCreate) SetNillableDeletedAt(v *time.Time) *ResumeScoreCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ResumeScoreCreate) SetID(v int64) *ResumeScoreCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ResumeScoreCreate) SetNillableID(v *int64) *ResumeScoreCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetResume sets the "resume" edge to the Resume entity.
func (_c *ResumeScoreCreate) SetResume(v *Resume) *ResumeScoreCreate {
	return _c.SetResumeID(v.ID)
}

// Mutation returns the ResumeScoreMutation object of the builder.
func (_c *ResumeScoreCreate) Mutation() *ResumeScoreMutation {
	return _c.mutation
}

// Save creates the ResumeScore in the database.
func (_c *ResumeScoreCreate) Save(ctx context.Context) (*ResumeScore, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResumeScoreCreate) SaveX(ctx context.Context) *ResumeScore {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResumeScoreCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResumeScoreCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ResumeScoreCreate) defaults() {
	if _, ok := _c.mutation.Score(); !ok {
		v := resumescore.DefaultScore
		_c.mutation.SetScore(v)
	}
	if _, ok := _c.mutation.Weight(); !ok {
		v := resumescore.DefaultWeight
		_c.mutation.SetWeight(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := resumescore.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := resumescore.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := resumescore.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResumeScoreCreate) check() error {
	if _, ok := _c.mutation.ResumeID(); !ok {
		return &ValidationError{Name: "resume_id", err: errors.New(`ent: missing required field "ResumeScore.resume_id"`)}
	}
	if _, ok := _c.mutation.TargetID(); !ok {
		return &ValidationError{Name: "target_id", err: errors.New(`ent: missing required field "ResumeScore.target_id"`)}
	}
	if _, ok := _c.mutation.TargetType(); !ok {
		return &ValidationError{Name: "target_type", err: errors.New(`ent: missing required field "ResumeScore.target_type"`)}
	}
	if _, ok := _c.mutation.Score(); !ok {
		return &ValidationError{Name: "score", err: errors.New(`ent: missing required field "ResumeScore.score"`)}
	}
	if _, ok := _c.mutation.Weight(); !ok {
		return &ValidationError{Name: "weight", err: errors.New(`ent: missing required field "ResumeScore.weight"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ResumeScore.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ResumeScore.updated_at"`)}
	}
	if len(_c.mutation.ResumeIDs()) == 0 {
		return &ValidationError{Name: "resume", err: errors.New(`ent: missing required edge "ResumeScore.resume"`)}
	}
	return nil
}

func (_c *ResumeScoreCreate) sqlSave(ctx context.Context) (*ResumeScore, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResumeScoreCreate) createSpec() (*ResumeScore, *sqlgraph.CreateSpec) {
	var (
		_node = &ResumeScore{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(resumescore.Table, sqlgraph.NewFieldSpec(resumescore.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TargetID(); ok {
		_spec.SetField(resumescore.FieldTargetID, field.TypeInt64, value)
		_node.TargetID = value
	}
	if value, ok := _c.mutation.TargetType(); ok {
		_spec.SetField(resumescore.FieldTargetType, field.TypeInt32, value)
		_node.TargetType = value
	}
	if value, ok := _c.mutation.Score(); ok {
		_spec.SetField(resumescore.FieldScore, field.TypeFloat64, value)
		_node.Score = value
	}
	if value, ok := _c.mutation.Weight(); ok {
		_spec.SetField(resumescore.FieldWeight, field.TypeFloat64, value)
		_node.Weight = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(resumescore.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(resumescore.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(resumescore.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if nodes := _c.mutation.ResumeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   resumescore.ResumeTable,
			Columns: []string{resumescore.ResumeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resume.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ResumeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ResumeScoreCreateBulk is the builder for creating many ResumeScore entities in bulk.
type ResumeScoreCreateBulk struct {
	config
	err      error
	builders []*ResumeScoreCreate
}

// Save creates the ResumeScore entities in the database.
func (_c *ResumeScoreCreateBulk) Save(ctx context.Context) ([]*ResumeScore, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ResumeScore, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResumeScoreMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResumeScoreCreateBulk) SaveX(ctx context.Context) []*ResumeScore {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResumeScoreCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResumeScoreCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
