// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cv2/internal/infra/ent/resume"
	"cv2/internal/infra/ent/resumescore"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ResumeCreate is the builder for creating a Resume entity.
type ResumeCreate struct {
	config
	mutation *ResumeMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *ResumeCreate) SetUserID(v int64) *ResumeCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *ResumeCreate) SetTenantID(v int64) *ResumeCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetFilePath sets the "file_path" field.
func (_c *ResumeCreate) SetFilePath(v string) *ResumeCreate {
	_c.mutation.SetFilePath(v)
	return _c
}

// SetFileName sets the "file_name" field.
func (_c *ResumeCreate) SetFileName(v string) *ResumeCreate {
	_c.mutation.SetFileName(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ResumeCreate) SetStatus(v int32) *ResumeCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ResumeCreate) SetNillableStatus(v *int32) *ResumeCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ResumeCreate) SetCreatedAt(v time.Time) *ResumeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ResumeCreate) SetNillableCreatedAt(v *time.Time) *ResumeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ResumeCreate) SetUpdatedAt(v time.Time) *ResumeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ResumeCreate) SetNillableUpdatedAt(v *time.Time) *ResumeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ResumeCreate) SetDeletedAt(v time.Time) *ResumeCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ResumeCreate) SetNillableDeletedAt(v *time.Time) *ResumeCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ResumeCreate) SetID(v int64) *ResumeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ResumeCreate) SetNillableID(v *int64) *ResumeCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddScoreIDs adds the "scores" edge to the ResumeScore entity by IDs.
func (_c *ResumeCreate) AddScoreIDs(ids ...int64) *ResumeCreate {
	_c.mutation.AddScoreIDs(ids...)
	return _c
}

// AddScores adds the "scores" edges to the ResumeScore entity.
func (_c *ResumeCreate) AddScores(v ...*ResumeScore) *ResumeCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddScoreIDs(ids...)
}

// Mutation returns the ResumeMutation object of the builder.
func (_c *ResumeCreate) Mutation() *ResumeMutation {
	return _c.mutation
}

// Save creates the Resume in the database.
func (_c *ResumeCreate) Save(ctx context.Context) (*Resume, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResumeCreate) SaveX(ctx context.Context) *Resume {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResumeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResumeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ResumeCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := resume.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := resume.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := resume.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := resume.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResumeCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Resume.user_id"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Resume.tenant_id"`)}
	}
	if _, ok := _c.mutation.FilePath(); !ok {
		return &ValidationError{Name: "file_path", err: errors.New(`ent: missing required field "Resume.file_path"`)}
	}
	if v, ok := _c.mutation.FilePath(); ok {
		if err := resume.FilePathValidator(v); err != nil {
			return &ValidationError{Name: "file_path", err: fmt.Errorf(`ent: validator failed for field "Resume.file_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FileName(); !ok {
		return &ValidationError{Name: "file_name", err: errors.New(`ent: missing required field "Resume.file_name"`)}
	}
	if v, ok := _c.mutation.FileName(); ok {
		if err := resume.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "Resume.file_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Resume.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Resume.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Resume.updated_at"`)}
	}
	return nil
}

func (_c *ResumeCreate) sqlSave(ctx context.Context) (*Resume, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResumeCreate) createSpec() (*Resume, *sqlgraph.CreateSpec) {
	var (
		_node = &Resume{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(resume.Table, sqlgraph.NewFieldSpec(resume.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(resume.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(resume.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.FilePath(); ok {
		_spec.SetField(resume.FieldFilePath, field.TypeString, value)
		_node.FilePath = value
	}
	if value, ok := _c.mutation.FileName(); ok {
		_spec.SetField(resume.FieldFileName, field.TypeString, value)
		_node.FileName = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(resume.FieldStatus, field.TypeInt32, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(resume.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(resume.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(resume.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if nodes := _c.mutation.ScoresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resume.ScoresTable,
			Columns: []string{resume.ScoresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resumescore.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ResumeCreateBulk is the builder for creating many Resume entities in bulk.
type ResumeCreateBulk struct {
	config
	err      error
	builders []*ResumeCreate
}

// Save creates the Resume entities in the database.
func (_c *ResumeCreateBulk) Save(ctx context.Context) ([]*Resume, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Resume, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResumeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResumeCreateBulk) SaveX(ctx context.Context) []*Resume {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResumeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResumeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
