// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"cv2/internal/infra/ent/resumeslot"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ResumeSlotCreate is the builder for creating a ResumeSlot entity.
type ResumeSlotCreate struct {
	config
	mutation *ResumeSlotMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *ResumeSlotCreate) SetUserID(v string) *ResumeSlotCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetMaxSlots sets the "max_slots" field.
func (_c *ResumeSlotCreate) SetMaxSlots(v int32) *ResumeSlotCreate {
	_c.mutation.SetMaxSlots(v)
	return _c
}

// SetNillableMaxSlots sets the "max_slots" field if the given value is not nil.
func (_c *ResumeSlotCreate) SetNillableMaxSlots(v *int32) *ResumeSlotCreate {
	if v != nil {
		_c.SetMaxSlots(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ResumeSlotCreate) SetCreatedAt(v time.Time) *ResumeSlotCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ResumeSlotCreate) SetNillableCreatedAt(v *time.Time) *ResumeSlotCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ResumeSlotCreate) SetUpdatedAt(v time.Time) *ResumeSlotCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ResumeSlotCreate) SetNillableUpdatedAt(v *time.Time) *ResumeSlotCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ResumeSlotCreate) SetDeletedAt(v time.Time) *ResumeSlotCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ResumeSlotCreate) SetNillableDeletedAt(v *time.Time) *ResumeSlotCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ResumeSlotCreate) SetID(v int64) *ResumeSlotCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ResumeSlotCreate) SetNillableID(v *int64) *ResumeSlotCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ResumeSlotMutation object of the builder.
func (_c *ResumeSlotCreate) Mutation() *ResumeSlotMutation {
	return _c.mutation
}

// Save creates the ResumeSlot in the database.
func (_c *ResumeSlotCreate) Save(ctx context.Context) (*ResumeSlot, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResumeSlotCreate) SaveX(ctx context.Context) *ResumeSlot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResumeSlotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResumeSlotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ResumeSlotCreate) defaults() {
	if _, ok := _c.mutation.MaxSlots(); !ok {
		v := resumeslot.DefaultMaxSlots
		_c.mutation.SetMaxSlots(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := resumeslot.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := resumeslot.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := resumeslot.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResumeSlotCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ResumeSlot.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := resumeslot.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "ResumeSlot.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MaxSlots(); !ok {
		return &ValidationError{Name: "max_slots", err: errors.New(`ent: missing required field "ResumeSlot.max_slots"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ResumeSlot.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ResumeSlot.updated_at"`)}
	}
	return nil
}

func (_c *ResumeSlotCreate) sqlSave(ctx context.Context) (*ResumeSlot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResumeSlotCreate) createSpec() (*ResumeSlot, *sqlgraph.CreateSpec) {
	var (
		_node = &ResumeSlot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(resumeslot.Table, sqlgraph.NewFieldSpec(resumeslot.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(resumeslot.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.MaxSlots(); ok {
		_spec.SetField(resumeslot.FieldMaxSlots, field.TypeInt32, value)
		_node.MaxSlots = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(resumeslot.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(resumeslot.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(resumeslot.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	return _node, _spec
}

// ResumeSlotCreateBulk is the builder for creating many ResumeSlot entities in bulk.
type ResumeSlotCreateBulk struct {
	config
	err      error
	builders []*ResumeSlotCreate
}

// Save creates the ResumeSlot entities in the database.
func (_c *ResumeSlotCreateBulk) Save(ctx context.Context) ([]*ResumeSlot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ResumeSlot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResumeSlotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResumeSlotCreateBulk) SaveX(ctx context.Context) []*ResumeSlot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResumeSlotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResumeSlotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
