// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cv2/internal/infra/ent/dimension"
	"cv2/internal/infra/ent/module"
	"cv2/internal/infra/ent/position"
	"cv2/internal/infra/ent/resume"
	"cv2/internal/infra/ent/resumescore"
	"cv2/internal/infra/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	dimensionFields := schema.Dimension{}.Fields()
	_ = dimensionFields
	// dimensionDescTitle is the schema descriptor for title field.
	dimensionDescTitle := dimensionFields[2].Descriptor()
	// dimension.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	dimension.TitleValidator = dimensionDescTitle.Validators[0].(func(string) error)
	// dimensionDescCreatedAt is the schema descriptor for created_at field.
	dimensionDescCreatedAt := dimensionFields[4].Descriptor()
	// dimension.DefaultCreatedAt holds the default value on creation for the created_at field.
	dimension.DefaultCreatedAt = dimensionDescCreatedAt.Default.(func() time.Time)
	// dimensionDescUpdatedAt is the schema descriptor for updated_at field.
	dimensionDescUpdatedAt := dimensionFields[5].Descriptor()
	// dimension.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	dimension.DefaultUpdatedAt = dimensionDescUpdatedAt.Default.(func() time.Time)
	// dimension.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	dimension.UpdateDefaultUpdatedAt = dimensionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// dimensionDescDeletedAt is the schema descriptor for deleted_at field.
	dimensionDescDeletedAt := dimensionFields[6].Descriptor()
	// dimension.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	dimension.DefaultDeletedAt = dimensionDescDeletedAt.Default.(time.Time)
	// dimensionDescID is the schema descriptor for id field.
	dimensionDescID := dimensionFields[0].Descriptor()
	// dimension.DefaultID holds the default value on creation for the id field.
	dimension.DefaultID = dimensionDescID.Default.(func() int64)
	moduleFields := schema.Module{}.Fields()
	_ = moduleFields
	// moduleDescTitle is the schema descriptor for title field.
	moduleDescTitle := moduleFields[1].Descriptor()
	// module.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	module.TitleValidator = moduleDescTitle.Validators[0].(func(string) error)
	// moduleDescDescription is the schema descriptor for description field.
	moduleDescDescription := moduleFields[2].Descriptor()
	// module.DefaultDescription holds the default value on creation for the description field.
	module.DefaultDescription = moduleDescDescription.Default.(string)
	// moduleDescCreatedAt is the schema descriptor for created_at field.
	moduleDescCreatedAt := moduleFields[3].Descriptor()
	// module.DefaultCreatedAt holds the default value on creation for the created_at field.
	module.DefaultCreatedAt = moduleDescCreatedAt.Default.(func() time.Time)
	// moduleDescUpdatedAt is the schema descriptor for updated_at field.
	moduleDescUpdatedAt := moduleFields[4].Descriptor()
	// module.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	module.DefaultUpdatedAt = moduleDescUpdatedAt.Default.(func() time.Time)
	// module.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	module.UpdateDefaultUpdatedAt = moduleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// moduleDescDeletedAt is the schema descriptor for deleted_at field.
	moduleDescDeletedAt := moduleFields[5].Descriptor()
	// module.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	module.DefaultDeletedAt = moduleDescDeletedAt.Default.(time.Time)
	// moduleDescID is the schema descriptor for id field.
	moduleDescID := moduleFields[0].Descriptor()
	// module.DefaultID holds the default value on creation for the id field.
	module.DefaultID = moduleDescID.Default.(func() int64)
	positionFields := schema.Position{}.Fields()
	_ = positionFields
	// positionDescParentID is the schema descriptor for parent_id field.
	positionDescParentID := positionFields[2].Descriptor()
	// position.DefaultParentID holds the default value on creation for the parent_id field.
	position.DefaultParentID = positionDescParentID.Default.(int64)
	// positionDescTitle is the schema descriptor for title field.
	positionDescTitle := positionFields[3].Descriptor()
	// position.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	position.TitleValidator = positionDescTitle.Validators[0].(func(string) error)
	// positionDescID is the schema descriptor for id field.
	positionDescID := positionFields[0].Descriptor()
	// position.DefaultID holds the default value on creation for the id field.
	position.DefaultID = positionDescID.Default.(func() int64)
	resumeFields := schema.Resume{}.Fields()
	_ = resumeFields
	// resumeDescFilePath is the schema descriptor for file_path field.
	resumeDescFilePath := resumeFields[3].Descriptor()
	// resume.FilePathValidator is a validator for the "file_path" field. It is called by the builders before save.
	resume.FilePathValidator = resumeDescFilePath.Validators[0].(func(string) error)
	// resumeDescFileName is the schema descriptor for file_name field.
	resumeDescFileName := resumeFields[4].Descriptor()
	// resume.FileNameValidator is a validator for the "file_name" field. It is called by the builders before save.
	resume.FileNameValidator = resumeDescFileName.Validators[0].(func(string) error)
	// resumeDescStatus is the schema descriptor for status field.
	resumeDescStatus := resumeFields[5].Descriptor()
	// resume.DefaultStatus holds the default value on creation for the status field.
	resume.DefaultStatus = resumeDescStatus.Default.(int32)
	// resumeDescCreatedAt is the schema descriptor for created_at field.
	resumeDescCreatedAt := resumeFields[6].Descriptor()
	// resume.DefaultCreatedAt holds the default value on creation for the created_at field.
	resume.DefaultCreatedAt = resumeDescCreatedAt.Default.(func() time.Time)
	// resumeDescUpdatedAt is the schema descriptor for updated_at field.
	resumeDescUpdatedAt := resumeFields[7].Descriptor()
	// resume.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	resume.DefaultUpdatedAt = resumeDescUpdatedAt.Default.(func() time.Time)
	// resume.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	resume.UpdateDefaultUpdatedAt = resumeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// resumeDescDeletedAt is the schema descriptor for deleted_at field.
	resumeDescDeletedAt := resumeFields[8].Descriptor()
	// resume.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	resume.DefaultDeletedAt = resumeDescDeletedAt.Default.(time.Time)
	// resumeDescID is the schema descriptor for id field.
	resumeDescID := resumeFields[0].Descriptor()
	// resume.DefaultID holds the default value on creation for the id field.
	resume.DefaultID = resumeDescID.Default.(func() int64)
	resumescoreFields := schema.ResumeScore{}.Fields()
	_ = resumescoreFields
	// resumescoreDescScore is the schema descriptor for score field.
	resumescoreDescScore := resumescoreFields[4].Descriptor()
	// resumescore.DefaultScore holds the default value on creation for the score field.
	resumescore.DefaultScore = resumescoreDescScore.Default.(float64)
	// resumescoreDescWeight is the schema descriptor for weight field.
	resumescoreDescWeight := resumescoreFields[5].Descriptor()
	// resumescore.DefaultWeight holds the default value on creation for the weight field.
	resumescore.DefaultWeight = resumescoreDescWeight.Default.(float64)
	// resumescoreDescCreatedAt is the schema descriptor for created_at field.
	resumescoreDescCreatedAt := resumescoreFields[6].Descriptor()
	// resumescore.DefaultCreatedAt holds the default value on creation for the created_at field.
	resumescore.DefaultCreatedAt = resumescoreDescCreatedAt.Default.(func() time.Time)
	// resumescoreDescUpdatedAt is the schema descriptor for updated_at field.
	resumescoreDescUpdatedAt := resumescoreFields[7].Descriptor()
	// resumescore.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	resumescore.DefaultUpdatedAt = resumescoreDescUpdatedAt.Default.(func() time.Time)
	// resumescore.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	resumescore.UpdateDefaultUpdatedAt = resumescoreDescUpdatedAt.UpdateDefault.(func() time.Time)
	// resumescoreDescDeletedAt is the schema descriptor for deleted_at field.
	resumescoreDescDeletedAt := resumescoreFields[8].Descriptor()
	// resumescore.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	resumescore.DefaultDeletedAt = resumescoreDescDeletedAt.Default.(time.Time)
	// resumescoreDescID is the schema descriptor for id field.
	resumescoreDescID := resumescoreFields[0].Descriptor()
	// resumescore.DefaultID holds the default value on creation for the id field.
	resumescore.DefaultID = resumescoreDescID.Default.(func() int64)
}
