// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AIRecord is the predicate function for airecord builders.
type AIRecord func(*sql.Selector)

// City is the predicate function for city builders.
type City func(*sql.Selector)

// Dictionary is the predicate function for dictionary builders.
type Dictionary func(*sql.Selector)

// Dimension is the predicate function for dimension builders.
type Dimension func(*sql.Selector)

// Module is the predicate function for module builders.
type Module func(*sql.Selector)

// Position is the predicate function for position builders.
type Position func(*sql.Selector)

// Resume is the predicate function for resume builders.
type Resume func(*sql.Selector)

// ResumeScore is the predicate function for resumescore builders.
type ResumeScore func(*sql.Selector)

// ResumeSlot is the predicate function for resumeslot builders.
type ResumeSlot func(*sql.Selector)
