// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Dimension is the predicate function for dimension builders.
type Dimension func(*sql.Selector)

// Module is the predicate function for module builders.
type Module func(*sql.Selector)

// Position is the predicate function for position builders.
type Position func(*sql.Selector)

// Resume is the predicate function for resume builders.
type Resume func(*sql.Selector)

// ResumeScore is the predicate function for resumescore builders.
type ResumeScore func(*sql.Selector)
