// Code generated by ent, DO NOT EDIT.

package ent

import (
	"cv2/internal/ent/position"
	"cv2/internal/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	positionFields := schema.Position{}.Fields()
	_ = positionFields
	// positionDescParentID is the schema descriptor for parent_id field.
	positionDescParentID := positionFields[2].Descriptor()
	// position.DefaultParentID holds the default value on creation for the parent_id field.
	position.DefaultParentID = positionDescParentID.Default.(int64)
	// positionDescTitle is the schema descriptor for title field.
	positionDescTitle := positionFields[3].Descriptor()
	// position.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	position.TitleValidator = positionDescTitle.Validators[0].(func(string) error)
	// positionDescID is the schema descriptor for id field.
	positionDescID := positionFields[0].Descriptor()
	// position.DefaultID holds the default value on creation for the id field.
	position.DefaultID = positionDescID.Default.(func() int64)
}
