// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	position "cv2/internal/handler/position"
	resume "cv2/internal/handler/resume"
	"cv2/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// Position options
					Method:  http.MethodGet,
					Path:    "/api/positions/options",
					Handler: position.OptionsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 生成简历
					Method:  http.MethodPost,
					Path:    "/api/resume/generate",
					Handler: resume.GenerateResumeHandler(serverCtx),
				},
				{
					// 查询生成任务状态
					Method:  http.MethodGet,
					Path:    "/api/resume/task/:task_id",
					Handler: resume.GetTaskStatusHandler(serverCtx),
				},
				{
					// 获取简历上传 POST Policy
					Method:  http.MethodPost,
					Path:    "/api/resume/upload/policy",
					Handler: resume.GetUploadPolicyHandler(serverCtx),
				},
				{
					// 获取简历上传预签名 URL
					Method:  http.MethodPost,
					Path:    "/api/resume/upload/presign",
					Handler: resume.GetUploadPresignURLHandler(serverCtx),
				},
			}...,
		),
	)
}
