// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	article "cv2/internal/handler/article"
	auth "cv2/internal/handler/auth"
	city "cv2/internal/handler/city"
	dictionary "cv2/internal/handler/dictionary"
	pay "cv2/internal/handler/pay"
	position "cv2/internal/handler/position"
	resume "cv2/internal/handler/resume"
	slot "cv2/internal/handler/slot"
	"cv2/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取运营文章详情
				Method:  http.MethodGet,
				Path:    "/api/article/:articleId",
				Handler: article.GetArticleHandler(serverCtx),
			},
			{
				// 获取运营文章列表
				Method:  http.MethodGet,
				Path:    "/api/article/list",
				Handler: article.ListArticlesHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/api/auth/login",
				Handler: auth.LoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 根据首字母获取城市
					Method:  http.MethodGet,
					Path:    "/api/cities/by-initials",
					Handler: city.GetCitiesByInitialsHandler(serverCtx),
				},
				{
					// 获取所有二级城市
					Method:  http.MethodGet,
					Path:    "/api/cities/level2",
					Handler: city.GetLevel2CitiesHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 根据类型获取字典
					Method:  http.MethodGet,
					Path:    "/api/dictionary/by-type",
					Handler: dictionary.GetDictionaryByTypeHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 查询订单状态
					Method:  http.MethodGet,
					Path:    "/api/pay/slot/order/:order_id",
					Handler: pay.GetSlotOrderHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// Position options
					Method:  http.MethodGet,
					Path:    "/api/positions/options",
					Handler: position.OptionsHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 获取简历详情
					Method:  http.MethodGet,
					Path:    "/api/resume/:resume_id",
					Handler: resume.GetResumeHandler(serverCtx),
				},
				{
					// 生成简历
					Method:  http.MethodPost,
					Path:    "/api/resume/generate",
					Handler: resume.GenerateResumeHandler(serverCtx),
				},
				{
					// 保存简历模块
					Method:  http.MethodPost,
					Path:    "/api/resume/module",
					Handler: resume.SaveModuleHandler(serverCtx),
				},
				{
					// 查询生成任务状态
					Method:  http.MethodGet,
					Path:    "/api/resume/task/:task_id",
					Handler: resume.GetTaskStatusHandler(serverCtx),
				},
				{
					// 上传简历文件解析
					Method:  http.MethodPost,
					Path:    "/api/resume/upload",
					Handler: resume.UploadResumeHandler(serverCtx),
				},
				{
					// 获取简历上传 POST Policy
					Method:  http.MethodPost,
					Path:    "/api/resume/upload/policy",
					Handler: resume.GetUploadPolicyHandler(serverCtx),
				},
				{
					// 获取简历上传预签名 URL
					Method:  http.MethodPost,
					Path:    "/api/resume/upload/presign",
					Handler: resume.GetUploadPresignURLHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// AI 帮写（SSE 流式返回）
					Method:  http.MethodPost,
					Path:    "/api/resume/ai-write",
					Handler: resume.AIWriteHandler(serverCtx),
				},
			}...,
		),
		rest.WithSSE(),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 创建席位购买订单
					Method:  http.MethodPost,
					Path:    "/api/slot/order",
					Handler: slot.CreateSlotOrderHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 席位支付回调（供支付微服务调用）
				Method:  http.MethodPost,
				Path:    "/api/pay/slot/notify",
				Handler: slot.SlotPayNotifyHandler(serverCtx),
			},
		},
	)
}
