// Code generated by ent, DO NOT EDIT.

package resumeslot

import (
	"cv2/internal/infra/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldEQ(FieldUserID, v))
}

// MaxSlots applies equality check predicate on the "max_slots" field. It's identical to MaxSlotsEQ.
func MaxSlots(v int32) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldEQ(FieldMaxSlots, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldEQ(FieldDeletedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldContainsFold(FieldUserID, v))
}

// MaxSlotsEQ applies the EQ predicate on the "max_slots" field.
func MaxSlotsEQ(v int32) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldEQ(FieldMaxSlots, v))
}

// MaxSlotsNEQ applies the NEQ predicate on the "max_slots" field.
func MaxSlotsNEQ(v int32) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldNEQ(FieldMaxSlots, v))
}

// MaxSlotsIn applies the In predicate on the "max_slots" field.
func MaxSlotsIn(vs ...int32) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldIn(FieldMaxSlots, vs...))
}

// MaxSlotsNotIn applies the NotIn predicate on the "max_slots" field.
func MaxSlotsNotIn(vs ...int32) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldNotIn(FieldMaxSlots, vs...))
}

// MaxSlotsGT applies the GT predicate on the "max_slots" field.
func MaxSlotsGT(v int32) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldGT(FieldMaxSlots, v))
}

// MaxSlotsGTE applies the GTE predicate on the "max_slots" field.
func MaxSlotsGTE(v int32) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldGTE(FieldMaxSlots, v))
}

// MaxSlotsLT applies the LT predicate on the "max_slots" field.
func MaxSlotsLT(v int32) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldLT(FieldMaxSlots, v))
}

// MaxSlotsLTE applies the LTE predicate on the "max_slots" field.
func MaxSlotsLTE(v int32) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldLTE(FieldMaxSlots, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.FieldNotNull(FieldDeletedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ResumeSlot) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ResumeSlot) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ResumeSlot) predicate.ResumeSlot {
	return predicate.ResumeSlot(sql.NotPredicates(p))
}
